### ISSUE TITLE
Не получается подключить к xamarin проекту

### ISSUE THREAD

**Issue by hram** [yandexmobile/yandex-ads-sdk-android#10]
Пытался подключить в android xamarin проект но безуспешно.
Получается инициализировать библиотеку
`YandexMetrica.activate(getApplicationContext(), API_KEY);`

Получается создать реквест
`AdRequest.builder().withParameters(parameters).build()`

Но не получается добавить банер
`NativeBannerView `

потому как он не импортируется из jar
Не импортируется по причине обфускации.
Класс наследуется от z класса и из за этого проблема.

Есть ли у вас желание настроить обфускацию таким образом чтобы вашу библиотеку можно было бы подключать к xamarin проектам?

**Comment by satsakul** [comment]
Спасибо за то, что сообщили о проблеме. Мы создали задачу на исследование данной проблемы и на поиск её решения.

**Comment by Babai-42** [comment]
Прошло уже столько лет. Сегодня пытался подключить к Xamarin Android библиотеку YandexADS, но видимо из за обфускации биндинг происходит некорректно. Не получается создать экземпляр (переменную) BannerAdView. Очень жалко, что Яндекс не поддерживает ни какие платформы кроме одной (для Андройд). Да еще и не дает людям сделать работу за них... Очень жалко.
