### ISSUE TITLE
Срабатывает клик при свайпе

### ISSUE THREAD

**Issue by gr33tx** [yandexmobile/yandex-ads-sdk-android#107]
Здравствуйте! Такая проблема: при свайпе влево/право/вверх на блоках Яндекс, Facebook, Statapp срабатывает клик. Как отключить это? Я устанавливаю нативный блок во фрагмент, который должен исчезать при свайпе влево или вправо. Но рекламный блок (все, что с ссылками: картинки, кнопка) перехватывает событие свайпа и срабатывает клик по ссылке в объявлении. В примере также происходит клик при свайпе. Спасибо!

**Comment by mobile-ads-github** [comment]
Добрый день, спасибо, что обратились с проблемой!

**Comment by gr33tx** [comment]
Здравствуйте. Удалось ли решить проблему?

**Comment by mobile-ads-github** [comment]
Здравствуйте

На данный момент задача еще в работе, не завершена.

**Comment by gr33tx** [comment]
Добрый день! Удалось ли исправить проблему? Есть ли обходной путь решения? Будет ли такой клик при подобном свайпе засчитываться как ложный, ведь их будет много при работе с приложением.

**Comment by gr33tx** [comment]
up

**Comment by mobile-ads-github** [comment]
Добрый день!
Проблему решили, фикс доступен под флагом с версии 5.0.0, сейчас проводятся эксперименты. Если Вы обновились до версии 5.0.0 - этого достаточно чтобы фикс заработал. Ориентировочно запустим на всех с 25.04

Случайные клики помечаются как случайные и не учитываются в конечной статистике

**Comment by mobile-ads-github** [comment]
Конфиг с включённым фиксом (для 5.0.0) раскатиться на всех пользователей примерно через 12 часов
