### ISSUE TITLE
Баннер занимает всю высоту активности

### ISSUE THREAD

**Issue by dubok79** [yandexmobile/yandex-ads-sdk-android#111]
Как правильно использовать AdSize.flexibleSize(width, height);
Раньше задавал ширину используя код:
```
private AdSize getAdSize() {
		Display display = activity.getWindowManager().getDefaultDisplay();
		DisplayMetrics outMetrics = new DisplayMetrics();
		display.getMetrics(outMetrics);

		float widthPixels = outMetrics.widthPixels;
		float density = outMetrics.density;

		int adWidth = (int) (widthPixels / density);

		return AdSize.flexibleSize(adWidth);
	}
```
Но теперь появился еще параметр height. Добавил его и теперь при загрузке рекламного блока часто он появляется на всю высоту, а иногда как и положено. Что я делаю не так? Спасибо

**Comment by mobile-ads-github** [comment]
Добрый день, спасибо, что обратились с проблемой!
Укажите пожалуйста, на какой версии столкнулись с проблемой, если это 5.0.0-alpha.1, то можете обратить внимание на нашу документацию по миграции https://yandex.ru/dev/mobile-ads/doc/android/quick-start-alpha/migration-guide-5-0-0.html.
Так же советую проверить значение, которое передается в качестве аргумента height, не может ли оно быть больше высоты активности?

**Comment by dubok79** [comment]
Да речь идет о версии 5.0.0-alpha.1. Проблема частично устранена путем задания размера как adView.setAdSize(AdSize.BANNER_320x100); - размер максимально возможного баннера выбранного в настройках площадки. Но это не удобно. Подскажите, пожалуйста, как правильно рассчитать высоту для использования ее в методе final AdSize flexibleAdSize = AdSize.flexibleSize(width, height); Спасибо.

**Comment by dubok79** [comment]
> Добрый день, спасибо, что обратились с проблемой! Укажите пожалуйста, на какой версии столкнулись с проблемой, если это 5.0.0-alpha.1, то можете обратить внимание на нашу документацию по миграции https://yandex.ru/dev/mobile-ads/doc/android/quick-start-alpha/migration-guide-5-0-0.html. Так же советую проверить значение, которое передается в качестве аргумента height, не может ли оно быть больше высоты активности?

Да речь идет о версии 5.0.0-alpha.1. Проблема частично устранена путем задания размера как adView.setAdSize(AdSize.BANNER_320x100); - размер максимально возможного баннера выбранного в настройках площадки. Но это не удобно. Подскажите, пожалуйста, как правильно рассчитать высоту для использования ее в методе final AdSize flexibleAdSize = AdSize.flexibleSize(width, height); Спасибо.

**Comment by mobile-ads-github** [comment]
В AdSize.flexibleSize(width, height) параметры width и hight задают максимальные размеры для баннера (но баннер может прийти и меньших размеров) и при выборе их значений уже стоит отталкиваться от Ваших потребностей в размере банерной рекламы.

**Comment by dubok79** [comment]
> В AdSize.flexibleSize(width, height) параметры width и hight задают максимальные размеры для баннера (но баннер может прийти и меньших размеров) и при выборе их значений уже стоит отталкиваться от Ваших потребностей в размере баннерной рекламы.

Какой тогда может быть максимальный размер баннера по высоте? 300?

**Comment by mobile-ads-github** [comment]
> > В AdSize.flexibleSize(width, height) параметры width и hight задают максимальные размеры для баннера (но баннер может прийти и меньших размеров) и при выборе их значений уже стоит отталкиваться от Ваших потребностей в размере баннерной рекламы.
> 
> Какой тогда может быть максимальный размер баннера по высоте? 300?

Это зависит от Вашего выбора, в принципе может прилететь и реклама, которая сможет заполнить и высоту 500 (обычно прилетает поменьше). Судя по Вашей проблеме Вы указываете значение height большее или равное высоте экрана и прилетает баннер, который заполняет его.

**Comment by dubok79** [comment]
> > > В AdSize.flexibleSize(width, height) параметры width и hight задают максимальные размеры для баннера (но баннер может прийти и меньших размеров) и при выборе их значений уже стоит отталкиваться от Ваших потребностей в размере баннерной рекламы.
> > 
> > 
> > Какой тогда может быть максимальный размер баннера по высоте? 300?
> 
> Это зависит от Вашего выбора, в принципе может прилететь и реклама, которая сможет заполнить и высоту 500 (обычно прилетает поменьше). Судя по Вашей проблеме Вы указываете значение height большее или равное высоте экрана и прилетает баннер, который заполняет его.

Да, разобрался. Спасибо. Проблему решил. Вопрос закрыт!
