### ISSUE TITLE
Внешний вид кнопки feedback

### ISSUE THREAD

**Issue by razvedos201** [yandexmobile/yandex-ads-sdk-android#113]
Здравствуйте! Столкнулся с проблемой, не могу изменить внешний вид кнопки feedback. .setFeedbackView(mBtnAdOptions); У mBtnAdOptions который является TextView заданы свойства в xml, но feedback в итоге использует свою картинку по умолчанию(3 белых кружка на темном фоне) как это можно исправить?Внешний вид других элементов поддается изменению.

**Comment by mobile-ads-github** [comment]
Здравствуйте

Внешний вид feedback ассета конфигурируется рекламной сетью Яндекса, на стороне приложения картинку в нем нельзя изменить.
