### ISSUE TITLE
Огромный баннер, вместо разрешенных форматов

### ISSUE THREAD

**Issue by OlegTarashkevich** [yandexmobile/yandex-ads-sdk-android#115]
Здравствуйте,

В приложении настроен показ баннеров. В моем рекламном аккаунте в одном из блоков разрешены форматы: 320×100, 320×50. 
Также в самом приложении задается размер:
`adView.setAdSize(AdSize.flexibleSize());`

Проблема в том, что приложение стало показывать огромный баннер, с размерами больше разрешенных в аккаунте.
Также видео реклама в баннере не разрешена, но по факту показывается.

С такой рекламой становится невозможно пользоваться приложением, пользователь недоволен, теряется доход.

<img width="254" alt="Screenshot 2022-03-11 at 11 41 33" src="https://user-images.githubusercontent.com/13828110/157833374-80f96206-4259-4e51-ad76-affb79aeda90.png">

<img width="287" alt="Screenshot 2022-03-11 at 11 46 01" src="https://user-images.githubusercontent.com/13828110/157833383-73235f85-fc74-4cd8-880b-532c56bec3bc.png">

![Screenshot_2022-03-11-00-05-27-46_f33ccee1236e0b912c6bd269dd5ffd7c](https://user-images.githubusercontent.com/13828110/157833111-5c62b205-7b87-49d4-a273-30a22494172e.jpg)

![Screenshot_2022-03-11-08-41-25-31_f33ccee1236e0b912c6bd269dd5ffd7c](https://user-images.githubusercontent.com/13828110/157834317-e5a652a4-47af-4dd5-be75-fc5f4dff8a0f.jpg)

**Comment by mobile-ads-github** [comment]
Здравствуйте

Скорее всего, вы попали в 1% эксперимент, в рамках которого мы планируем отказываться от размера баннера, задаваемого в Партнерском Интерфейсе, в пользу настроек, определяемых на стороне приложения. На данный момент эксперимент окончен.

В вашем случае использование ```AdSize.flexibleSize();``` говорит о том, что реклама может подбираться любого размера. Если вы хотите ограничить размер рекламы или зафиксировать его, то рекомендуем использовать другое API - ```AdSize(width, height);```
https://yandex.ru/dev/mobile-ads/doc/android/ref/com/yandex/mobile/ads/banner/AdSize.html#AdSize-int-int-

**Comment by OlegTarashkevich** [comment]
Да, в коде приложения используется AdSize.flexibleSize();
Но в аккаунте рекламной сети установлены допустимые размеры.

1. Как мне ограничить высоту баннера удаленно? Полноэкранный формат
занимает почти все место и это недопустимо.
2. Является ли эксперимент законченным или в будущем полноэкранный баннер
появится снова?
3. Получается в моем случае придется отключить блок этого баннера полностью
от показа, чтобы не допустить рекламу во всю доступную высоту? И затем
публиковать новую версию приложения с новым баннером, у которого программно
задана высота и ширина?

У меня около 3-4 приложений используют AdSize.flexibleSize(); и публикация
новой версии не планировалась. Это довольно затратно по времени, приложения
проходят цикл проверки перед публикацией и из-за размера такой рекламы
могут быть забанены на Google play.
