### ISSUE TITLE
AdSize.stickySize vs AdSize.flexibleSize for banner

### ISSUE THREAD

**Issue by OlegTarashkevich** [yandexmobile/yandex-ads-sdk-android#118]
Здравствуйте,

Прочитал документацию, но не понял отличие в размерах для баннеров
https://yandex.com/dev/mobile-ads/doc/android/quick-start/adaptive-banner.html

1. В каких единицах измерения устанавливаются размеры баннера: px, dp, etc.?
2. Чем отличается размер, например AdSize.stickySize(400) от AdSize.flexibleSize(400) ?
2.1.  Какая максимально возможная высота будет у этих баннеров?
3. Где найти тестовые id блоков для тестирования AdSize.stickySize и AdSize.flexibleSize? Без тестирования не хочется отправлять приложение на публикацию.

**Comment by OlegTarashkevich** [comment]
Решил использовать AdSize.flexibleSize. Нарисовался баннер с маленькой высотой, но занял всю предоставленную высоту.
```
    private AdSize getYandexAdSize(ViewGroup container) {
        if (yandexAdSize == null) {
            int width = getContainerWidth(container);
            int height = width/2;
            yandexAdSize = AdSize.flexibleSize(width, height);
        }
        return yandexAdSize;
    }
```
![Screenshot_20220315_225011](https://user-images.githubusercontent.com/13828110/158460427-2a5ff729-cf47-425c-b447-6516725aeb44.png)


Если использовать AdSize.stickySize(), то баннер не занимает всю ширину, но может забрать излишнюю высоту. Непонятно как ограничить высоту.
```
    private AdSize getYandexAdSize(ViewGroup container) {
        if (yandexAdSize == null) {
            int width = getContainerWidth(container);
            yandexAdSize = AdSize.stickySize(width);
        }
        return yandexAdSize;
    }
```
![Screenshot_20220315_224240](https://user-images.githubusercontent.com/13828110/158460859-8f58e3e7-dd31-4f09-8014-215c455c30f2.png)

Расчет ширины:
```
    protected int getContainerWidth(@NonNull final ViewGroup container) {
        // Determine the screen width (less decorations) to use for the ad width.
        DisplayMetrics outMetrics = Resources.getSystem().getDisplayMetrics();
        float density = outMetrics.density;
        float adWidthPixels = container.getWidth();

        // If the ad hasn't been laid out, default to the full screen width.
        if (adWidthPixels == 0) {
            adWidthPixels = outMetrics.widthPixels;
        }

        int adWidth = (int) (adWidthPixels / density);
        return adWidth;
    }
```

**Comment by OlegTarashkevich** [comment]
Благодарю за ответ.

Подскажите пожалуйста, что имеет больший приоритет: формат баннера, установленный в "Партнерском интерфейсе" или размер баннера установленный программно в коде приложения?

Например:
В коде установлен формат AdSize.BANNER_320x50, а в "Партнерском интерфейсе" адаптивный. 
В коде установлен формат AdSize.stickySize(width), а в "Партнерском интерфейсе" 320x50. 
Какие баннеры будут показаны в этих случаях?


Правильно ли я понимаю, чтобы высота у формата AdSize.stickySize была максимально возможной 90, нужно обновить версию SDK до 5.0.0-beta.1 и выше? А если версия SDK 4.5.0, баннер может быть во весь экран смартфона?

**Comment by mobile-ads-github** [comment]
Здравствуйте

В скором времени в Партнерском интерфейсе планируется отказ от размеров и применяться будут только размеры из кода. На данный момент еще работает логика выбора минимального размера из доступных: и из кода, и из Партнерского интерфейса. Например,
* В коде установлен формат AdSize.BANNER_320x50, а в "Партнерском интерфейсе" адаптивный => баннеры будут 320x50
* В коде установлен формат AdSize.stickySize(width), а в "Партнерском интерфейсе" 320x50 => баннеры будут 320x50. В скором будущем тут будет подбираться баннер с width x (максимальная высота 90)


Мы рекомендуем вам обновиться до версии 5.0.0-beta.1 и выше, но в ближайшие дни и для старых версий сдк AdSize.stickySize будет ограничен с верху максимальной высотой 90.

**Comment by OlegTarashkevich** [comment]
Благодарю
