### ISSUE TITLE
Плагин для cordova/capacitor/ionic

### ISSUE THREAD

**Issue by maximnara** [yandexmobile/yandex-ads-sdk-android#121]
Всем привет!
Позволю прорекламировать немного свою работу, если кому-то нужен плагин для cordova совместимых проектов, для таких фреймворков как ionic framework (capacitor), то вот ссылка: https://github.com/maximnara/cordova-plugin-yandex-ads

Думаю сам РСЯ вряд ли запилит такой плагин, а желающих пользоваться РСЯ достаточно в РФ учитывая происходящие изменения.
Буду благодарен за коммиты и PR.

**Comment by mobile-ads-github** [comment]
Здравствуйте
Разработка официального плагина в ближайшее время не планируется. Также поддержка неофициальных плагинов не осуществляется.
