### ISSUE TITLE
AppMetrica

### ISSUE THREAD

**Issue by OlegTarashkevich** [yandexmobile/yandex-ads-sdk-android#123]
Здравствйте,

сделайте пожалуйста возможность работы SDK без AppMetrica.

Ранее из-за нее пришлось менять инициализацию во многих приложениях из-за отдельного процесса, а теперь есть риски будущих возможных проблем от Google.
С одной стороны добавляешь рекламную SDKs, а как ненужный багаж получаешь AppMetrica.

Причина:
https://devby.io/news/ft-appmetrica-yandeksa-ugrozhaet-bezopasnosti-dannyh-polzovatelei-yandeks-nichego-podobnogo-1648554936

Пока это новости, но они влияют на общественность, а она на google.

**Comment by mobile-ads-github** [comment]
AppMetrica необходима для корректной работы рекламного SDK. AppMetrica соблюдает стандартны безопасности данных. Существование, логика и принципы работы платформы соответсвуют политикам Google Play и App Store.
