### ISSUE TITLE
AdRequestError : Invalid server response code

### ISSUE THREAD

**Issue by toffeantyri** [yandexmobile/yandex-ads-sdk-android#125]
Проблема с Interstitial ads в приложении
Настраивал по инструкции. 
Banner и RewardAd работают нормально, interstitial никак не хочет загружается. 
SetADUnitID с тестовым Id

**Comment by mobile-ads-github** [comment]
Добрый день! Подскажите, какой adUnitId используете для запроса Interstitial рекламы.

**Comment by toffeantyri** [comment]
> Добрый день! Подскажите, какой adUnitId используете для запроса Interstitial рекламы.


Пробовал эти : 
R-M-DEMO-400x240-context

R-M-DEMO-480x320

**Comment by toffeantyri** [comment]
​    implementation ​'​com.yandex.android:mobileads:5.0.0-alpha.2​' 
 ​    implementation ​'​com.yandex.android:mobmetricalib:4.1.1​'

Билд

**Comment by mobile-ads-github** [comment]
Попробуйте использовать блок из  нашего публичного примера: https://github.com/yandexmobile/yandex-ads-sdk-android/blob/master/YandexMobileAdsExample/app/src/main/java/com/yandex/ads/sample/yandex/interstitial/InterstitialYandexAdsActivity.kt.
Блок: R-M-DEMO-interstitial

**Comment by toffeantyri** [comment]
> Попробуйте использовать блок из  нашего публичного примера: https://github.com/yandexmobile/yandex-ads-sdk-android/blob/master/YandexMobileAdsExample/app/src/main/java/com/yandex/ads/sample/yandex/interstitial/InterstitialYandexAdsActivity.kt.
> Блок: R-M-DEMO-interstitial



Спасибо, это помогло. 
При внедрении яедекс рекламы использовал информацию из статьи 

https://yandex.ru/dev/mobile-ads/doc/android/quick-start/interstitial.html#add-interstitial
В которой указанны нерабочие id демо-блоков.
