### ISSUE TITLE
Ошибка: Code 1. Banner rendering failed with timeout

### ISSUE THREAD

**Issue by e1e5en-gd** [yandexmobile/yandex-ads-sdk-android#128]
Получаю ошибку при попытке отобразить баннерную рекламу.
`Code 1. Banner rendering failed with timeout`
Полноэкранная отображается нормально.

**Comment by mobile-ads-github** [comment]
Добрый день, такая ошибка скорее всего возникает при загрузке html рекламы
Мы вставляем код баннера в вебвью и ожидаем когда он сообщит о готовности
Видимо этого не происходит
Могли бы вы приложить ответ из ручки https://mobile.yandexadexchange.net/v4/ad чтобы можно было разобраться?

**Comment by e1e5en-gd** [comment]
> Могли бы вы приложить ответ из ручки https://mobile.yandexadexchange.net/v4/ad чтобы можно было разобраться?

Всё что я получаю это _Service unavailable_. Может я Вас не правильно понял, что именно нужно сделать.

**Comment by mobile-ads-github** [comment]
![Screenshot 2022-04-20 at 11 03 49 AM](https://user-images.githubusercontent.com/31896236/164181096-78c7ef8f-c91f-4ba9-ae64-2a5a6bbaa51d.png)

Ошибка Banner rendering failed with timeout возможна только после того как придет ответ с рекламой (из ручки /v4/ad).

Вот так выглядит сессия где произошел запрос за рекламой (v4/ad).
После чего была попытка загрузить в вебвью рекламный код (второй запрос) - он провалился, поэтому случится ошибка Banner rendering failed with timeout.

У вас скорее всего нет сетевых проблем, поэтому вероятнее, что дело в самом баннере, который пришел из ручки /v4/ad - его-то мы и хотим увидеть (на приложенном скриншоте для этого надо провалиться в response и скопировать текст ответа).

Если возможности записать ответ совсем нет - то можете сказать banner_id - мы попробуем отловить проблемные баннера.

**Comment by e1e5en-gd** [comment]
Написал на почту

**Comment by yaugenka** [comment]
Наблюдаю такую же проблему. ID блоков отправил на почту.
