### ISSUE TITLE
Side effect with yandex banner. Android 10 

### ISSUE THREAD

**Issue by toffeantyri** [yandexmobile/yandex-ads-sdk-android#130]
Столкнулся с сайд эффектом : 
Как должно быть:
В приложении, Активити запускает foregroundservice (media player играет музыку в сервисе). 
 Сворачиваешь Активити (home),
Затем смахиваешь  приложение из списка последних приложений. 
Активити killed. Service - работает как служба переднего плана (foregroundservice). 

Для banner в Активити , забыл указать метод banner.destroy()

Работало всё как надо кроме: 
Смахиваешь Активити из списка последних приложений, foregroundservice тоже killed при этом метод onDestroy() для сервиса не вызывается.

Добавление banner.destroy() исправило ситуацию.
Что это, side-эффект ?) 
Каким образом banner влияет на foregroundservice?

**Comment by toffeantyri** [comment]
https://github.com/toffeantyri/radiostationvedaradio

Commit 250422 0.465 - пример приложения

**Comment by mobile-ads-github** [comment]
Здравствуйте, спасибо что сообщили о проблеме, будем разбираться

**Comment by mobile-ads-github** [comment]
Здравствуйте, не смогли найти возможной взаимосвязи между BannerAdView.destroy() и lifecycle сервиса.
