### ISSUE TITLE
Креш при использовании версии 5.1.0

### ISSUE THREAD

**Issue by Qhash** [yandexmobile/yandex-ads-sdk-android#138]
Здравствуйте. После обновления на версию 5.1.0 массово стали сыпаться креши.
`Fatal Exception: java.lang.IllegalStateException: Ad Activity into the AndroidManifest.xml is integrated wrong
       at com.yandex.mobile.ads.impl.wf.a(SourceFile:36)
       at com.yandex.mobile.ads.impl.r50.<init>(SourceFile:2)
       at com.yandex.mobile.ads.interstitial.InterstitialAd.<init>(SourceFile:1)`

Похожий креш видели и при обновлении до 5.0.0 и тоже массовый
`Fatal Exception: java.lang.IllegalStateException: Ad Activity into the AndroidManifest.xml is integrated wrong
       at com.yandex.mobile.ads.impl.qf.a(SourceFile:36)
       at com.yandex.mobile.ads.impl.b50.<init>(SourceFile:2)
       at com.yandex.mobile.ads.interstitial.InterstitialAd.<init>(SourceFile:1)`

**Comment by mobile-ads-github** [comment]
Здравствуйте! Спасибо за вопрос. 
Данная ошибка возникает при ошибке интеграции нашей библиотеки, в случае отсутствия одной из activity в манифесте.
Подскажите, не вырезаете ли вы из манифеста что-то лишнее?

**Comment by Qhash** [comment]
@mobile-ads-github ничего не вырезаем, при переходе с версии 4.5.0 на 5.0.0 и 5.1.0 манифест приложение не подвергался изменениям.

**Comment by mobile-ads-github** [comment]
Предоставленных ранее данных недостаточно, для более детального разбора можем предложить вам отправить нам на почту [mobile-ads-github@yandex-team.ru](mailto:mobile-ads-github@yandex-team.ru) сборку вашего приложения.

**Comment by mobile-ads-github** [comment]
Добрый день. Спасибо, нашли потенциальную проблему, исправление будет выпущено в следующем релизе рекламного SDK.

**Comment by thunderstorms-plus** [comment]
> Добрый день. Спасибо, нашли потенциальную проблему, исправление будет выпущено в следующем релизе рекламного SDK.

А что нашли?
У меня тааая же ошибка,  почти неделю никак не решу проблему...

**Comment by mobile-ads-github** [comment]
Добрый день, проблема исправлена в версии рекламного SDK 5.4.0.
