### ISSUE TITLE
RuntimeException: Package manager has died at at com.yandex.mobile.ads.k.a.a(SourceFile:22)

### ISSUE THREAD

**Issue by DimaKoz** [yandexmobile/yandex-ads-sdk-android#14]
Добрый день.
Получил [крешлог](https://github.com/yandexmobile/yandex-ads-sdk-android/files/1276685/log.txt). Падения единичные. 
Происходит в основном на рутированных устройствах.

В проекте используется :
com.yandex.android:mobmetricalib:2.73
com.yandex.android:mobileads:2.60

**Comment by satsakul** [comment]
Большое спасибо за предоставленную информацию. Завели задачу на исследование данной проблемы.

**Comment by satsakul** [comment]
Добрый день. Вышел релиз версии 2.70, в которой проблема была устранена. Спасибо
