### ISSUE TITLE
AppMetrica: Your app includes non compliant SDK version

### ISSUE THREAD

**Issue by prilaga** [yandexmobile/yandex-ads-sdk-android#141]
Здравствуйте @mobile-ads-github @satsakul ,

В консоли разработчика Google Play пришло уведомление об использовании device location библиотекой appmetrica без разрешения пользователя. см. скриншот.

implementation "com.yandex.android:mobmetricalib:4.0.0"
implementation "com.yandex.android:mobileads:4.5.0"

Но все разрешения на определение местоположение я убирал принудительно в манифесте приложения:
```
    <uses-permission
        android:name="android.permission.ACCESS_COARSE_LOCATION"
        tools:node="remove" />
    <uses-permission
        android:name="android.permission.ACCESS_FINE_LOCATION"
        tools:node="remove" />
    <uses-permission
        android:name="android.permission.ACCESS_BACKGROUND_LOCATION"
        tools:node="remove" />
```

Более того, сделал реверс опубликованного apk и не нашел разрешение о местоположении.
1. Может разрешение uses-permission android:name="android.permission.ACCESS_WIFI_STATE" каким-либо образом влияет на сбор местоположения или ведется сбор местоположения по ip адресу?
2. Есть ли какие-то проблемы с appmetrica?
3. Как ее можно абсолютно убрать из проектов (уже просил ранее: https://github.com/yandexmobile/yandex-ads-sdk-android/issues/129) ?
4. Собирает ли mobileads:5.1.1 какие-либо чувствительные пользовательские данные, о которых нужно предупредить пользователя? 
5. Актуально ли выключение контекстных данных в android manifest для mobileads:5.1.1 ?
```
<meta-data
    android:name="@string/yandex_ads_context"
    android:value="@string/yandex_ads_context_do_not_parse"/>
```

<img width="1045" alt="Screenshot 2022-06-29 at 00 42 46" src="https://user-images.githubusercontent.com/13828110/176311044-49598d6a-41ec-4ccb-9391-d27c72751244.png">

**Comment by mobile-ads-github** [comment]
Здравствуйте,
Временное решение это подключить версию Апметрики 5.0.0 https://yandex.ru/dev/mobile-ads/doc/android/quick-start/android-ads-component.html `implementation 'com.yandex.android:mobmetricalib:5.0.0'`. В следующем релизе сдк 5.2.0 мы перейдем на эту версию, и не нужно будет ничего подключать.
