### ISSUE TITLE
Проблема с proguard и minify

### ISSUE THREAD

**Issue by alxiw** [yandexmobile/yandex-ads-sdk-android#142]
Используем ваш SDK версии 5.1.0 для показа рекламы через медиацию из нашей сети на Yandex. В нашем приложении столкнулись с проблемой при показе баннеров размера 320x50 и rewarded. После загрузки и показа рекламы не срабатывает клик по ней, то есть не вызываются методы BannerAdEventListener#onAdClicked() и RewardedAdEventListener#onAdClicked() соответственно, в отличие от interstitial и native. 

Причём происходит это именно на релизной версии, где мы используем proguard и minify:

```
minifyEnabled true
proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
```

причём если в build.gradle (для app) убрать хотя-бы одну из этих строк - проблема пропадает.

Подскажите, может ли здесь быть проблема на вашей стороне?

**Comment by mobile-ads-github** [comment]
Добрый день, попробуйте пожалуйста обновить версию рекламного SDK до 5.2.0.
Также стоит попробовать использовать при сборке приложения Android Gradle Plugin 7.2.1 и Gradle Wrapper 7.4.2.
