### ISSUE TITLE
Не хватает метода unbindAd?

### ISSUE THREAD

**Issue by xblonde** [yandexmobile/yandex-ads-sdk-android#15]
Добрый день.
При использовании `NativeAppInstallAd` и `NativeContentAd` в `RecyclerView` столкнулись с такой проблемой. 
Поскольку `RecyclerView` переиспользует `View` при прокрутке; в случае, если прокрутка списка происходит быстрее, чем загрузка изображений, на карточке рекламы может на какое-то время появляться нерелевантное изображение (из предыдущей рекламы). 
Есть ли какой-то способ прерывать загрузку изображений?

**Comment by satsakul** [comment]
Добрый день. 
Не могли бы Вы сообщить версию используемой Yandex Mobile Ads SDK?

**Comment by xblonde** [comment]
Версия 2.60

**Comment by satsakul** [comment]
Не могли бы Вы попробовать воспроизвести данную проблему на тестовом примере
https://github.com/yandexmobile/yandex-ads-sdk-android/tree/master/Examples/NativeTemplatesRecyclerViewExample?

**Comment by xblonde** [comment]
Проблема воспроизводится на тестовом примере при подстановке актуального `blockId`.

**Comment by satsakul** [comment]
Скажите, пожалуйста, это происходит при загрузке изображений автоматическим или ручным способом?

**Comment by xblonde** [comment]
При загрузке ручным способом. Метод `NativeGenericAd.loadImages` вызывается в `Adapter. onBindViewHolder`

**Comment by satsakul** [comment]
В Yandex Mobile Ads SDK аналога метода unbindAd нет, так как мы сами производим очистку вью при каждом новом байндинге. Скорее всего проблема возникла в алгоритме ручной догрузки изображений. 
Большое спасибо за предоставленную информацию. Мы постараемся исправить данную проблему в ближайших версиях Yandex Mobile Ads SDK.
