### ISSUE TITLE
Не отображается баннерная реклама

### ISSUE THREAD

**Issue by XJIOP** [yandexmobile/yandex-ads-sdk-android#152]
Не отображается баннерная реклама от слова совсем, тестировал в эмуляторе Android Studio.

build.gradle
```
com.yandex.android:mobileads:5.2.0
com.yandex.android:mobmetricalib:5.0.0
```

MobileAds.initialize находится в Application.class, по логам yandex loaded вызывается два раза
```
com.yandex.mobile.ads.common.MobileAds.initialize(this, () -> {
                    Log.d(TAG, "yandex loaded");
                });
```

Код в Activity, пробовал так же свой R-M-XXXX-X результата все равно нет.
```
mYandexAdView = findViewById(R.id.adYView);
mYandexAdView.setAdSize(com.yandex.mobile.ads.banner.AdSize.BANNER_320x50);
mYandexAdView.setAdUnitId("R-M-DEMO-320x50");

com.yandex.mobile.ads.common.AdRequest adRequest = new com.yandex.mobile.ads.common.AdRequest.Builder().build();
mYandexAdView.loadAd(adRequest);
```

В логах видно только это
```
I/AppMetrica: Initializing of Metrica, Release type, Version 5.0.0, API Level 105, Dated 18.05.2022.
W/ideoapp:Metric: Class com.yandex.metrica.impl.ob.Ni failed lock verification and will run slower.
I/AppMetrica: Activate reporter with APIKey 322a737a-xxxx-xxxx-xxxx-xxxxxxxx1db6
I/AppMetrica: Activate reporter with APIKey 20799a27-xxxx-xxxx-xxxx-xxxxxxxx4180
I/AppMetrica-Attribution: Choosing distribution data: ClidsInfo(chosen=Candidate(clids=null, source=APP), candidates=[Candidate(clids=null, source=APP)])
W/ideoapp:Metric: Class com.yandex.metrica.impl.ob.Ni failed lock verification and will run slower.
D/Volley: [7585] v41.a: Changing log tag to Yandex Mobile Ads
```

BannerAdEventListener не показывает вообще  никаких результатов.

**Comment by mobile-ads-github** [comment]
Добрый день.
Вы не могли бы записать сетевую сессию от запуска приложения до попытки загрузки баннера включительно и прислать для более детального разбора на нашу почту [mobile-ads-github@yandex-team.ru](mailto:mobile-ads-github@yandex-team.ru)?
Спасибо за обращение.

**Comment by XJIOP** [comment]
Извиняюсь, была моя ошибка в коде. Баннер отображается нормально.

**Comment by XJIOP** [comment]
Извиняюсь, была моя ошибка в коде. Баннер отображается нормально. У меня только один вопрос, баннерную рекламу нужно вручную обновлять, или она меняется автоматически как в admob? От: mobile-ads-githubОтправлено: 4 августа 2022 г. в 18:32Кому: yandexmobile/yandex-ads-sdk-androidКопия: Denis Shirokov; AuthorТема: Re: [yandexmobile/yandex-ads-sdk-android] Не отображается баннерная реклама (Issue #152) Добрый день.Вы не могли бы записать сетевую сессию от запуска приложения до попытки загрузки баннера включительно и прислать для более детального разбора на нашу почту ***@***.***?Спасибо за обращение.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by mobile-ads-github** [comment]
Добрый день. 
По Вашему вопросу насчет автообновления баннерной рекламы: 
Нужно реализовать автообновление вручную, в Sdk этого не предусмотрено.

**Comment by XJIOP** [comment]
Спасибо.  Есть одна проблема, я скрываю баннер в видео плеереmYandexAdView.setVisibility(View.GONE);  и при повороте экрана баннер становится видимым, так должно быть? Как мне правильно скрывать баннер там где его не должно быть? На активити с видео плеером, в манифесте уставленоandroid:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" пробовал <activity            android:name="com.yandex.mobile.ads.common.AdActivity"            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" /> не помогает.  От: mobile-ads-githubОтправлено: 5 августа 2022 г. в 11:48Кому: yandexmobile/yandex-ads-sdk-androidКопия: Denis Shirokov; State changeТема: Re: [yandexmobile/yandex-ads-sdk-android] Не отображается баннерная реклама (Issue #152) Добрый день.По Вашему вопросу насчет автообновления баннерной рекламы:Нужно реализовать автообновление вручную, в Sdk этого не предусмотрено.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by mobile-ads-github** [comment]
Добрый день. Спасибо за репорт, есть недоработка  в рекламном SDK. В качестве временного решения, стоит сделать дополнительный контейнер над BannerAdView и устанавливать видимость со стороны приложения на этом контейнере.
