### ISSUE TITLE
Native ad with strange view

### ISSUE THREAD

**Issue by OlegTarashkevich** [yandexmobile/yandex-ads-sdk-android#158]
Здравствуйте,

Как можно убрать или изменить фон view "три точки" для нативной рекламы?
Эта view имеет прозрачность, которую нельзя изменить.
В моем случае под ней видна часть рамки, сильно бросается в глаза, что визуально некрасиво.

Надеюсь на скорый ответ.

 
![Screenshot_20220907_114709](https://user-images.githubusercontent.com/13828110/188849760-cc010eb0-08e2-4018-a44e-ce58a44d24df.png)

**Comment by mobile-ads-github** [comment]
Добрый день!
Можно изменить на черную/белую непрозрачную подложку используя следующий код:
```Java
final NativeAdLoader loader = new NativeAdLoader(this);
final HashMap<String, String> parameters = new HashMap<String, String>(){{
	put("feedback_image", "feedback_light_dots");
}};
final NativeAdRequestConfiguration nativeAdRequestConfiguration =
	new NativeAdRequestConfiguration.Builder("R-M-DEMO-native-i")
		.setParameters(parameters)
mNativeAdLoader.loadAd(nativeAdRequestConfiguration);
```
Вместо `feedback_light_dots` можно передать `feedback_dark_dots`.

**Comment by OlegTarashkevich** [comment]
Благодарю за быстрый ответ!

**Comment by OlegTarashkevich** [comment]
Жаль, что нельзя менять фон на уровне xml, т.к. у меня есть переключение темной и светлой темы.

**Comment by mobile-ads-github** [comment]
Поддержка темной темы для feedback ассета находится в разработке. Появится в одной из следующих версий SDK.
