### ISSUE TITLE
java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by MolokovMobile** [yandexmobile/yandex-ads-sdk-android#16]
Здравствуйте.
В версии 2.61 появилась ошибка, которой в 2.41 не было. До 2.61 версии не пробовал, возможно, ошибка появилась ранее. Используется совместно с метрикой 2.73.

java.util.concurrent.RejectedExecutionException: 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
  at java.util.concurrent.ThreadPoolExecutor.reject (ThreadPoolExecutor.java:793)
  at java.util.concurrent.ThreadPoolExecutor.execute (ThreadPoolExecutor.java:1339)
  at java.util.concurrent.Executors$DelegatedExecutorService.execute (Executors.java:583)
  at com.yandex.mobile.ads.s.a (s.java)
  at com.yandex.mobile.ads.s.b (s.java)
  at com.yandex.mobile.ads.s.a (s.java)
  at com.yandex.mobile.ads.ad.loadAd (ad.java)
  at com.yandex.mobile.ads.AdView.loadAd (AdView.java)

Android 5.1 | 16 | 36,4 %
Android 6.0 | 10 | 22,7 %
Android 5.0 | 6 | 13,6 %
Android 4.2 | 5 | 11,4 %
Android 7.1 | 3 | 6,8 %
Android 7.0 | 2 | 4,5 %
Android 4.4 | 2 | 4,5 %

**Comment by satsakul** [comment]
Большое спасибо за предоставленную информацию. 
Мы завели задачу на исследование данной проблемы. 

Не могли бы Вы сообщить как Вы выполняете загрузку рекламных объявлений? Вы загружаете большое кол-во объявлений сразу?

**Comment by MolokovMobile** [comment]
Загружается один баннер, через 30-40 секунд обновляется через loadAd().
До загрузки баннера может загружаться полноэкранная. Даётся несколько секунд на загрузку, если успешно, то показывается полноэкранная, а баннер не запрашивается совсем, иначе запрашивается баннер.
В самом приложении может быть запущено несколько AsyncTask одновременно.

**Comment by satsakul** [comment]
Работа с AdView происходит на UI потоке?

**Comment by MolokovMobile** [comment]
Да, только UI поток.
Всего около 90 повторов за 2 недели. Ошибка не массовая, самому воспроизвести не удалось.

**Comment by satsakul** [comment]
Большое спасибо за предоставленную информацию. 
Мы завели задачу на исследование данной проблемы.

**Comment by satsakul** [comment]
В последних версиях SDK проблемы быть не должно. Спасибо.
