### ISSUE TITLE
REQUEST_INSTALL_PACKAGES в com.yandex.mobile.ads.mediation.mintegral

### ISSUE THREAD

**Issue by Qhash** [yandexmobile/yandex-ads-sdk-android#168]
Добрый день. Вчера GooglePlay прислал предупреждение, с требованием удалить пермишн REQUEST_INSTALL_PACKAGES.
В ходе поиска его по проекту, он был обнаружен в одном месте, а именно в медиации минтеграла. 
`implementation 'com.yandex.ads.mediation:mobileads-mintegral:15.8.01.2'
`
![image](https://user-images.githubusercontent.com/2272910/195581646-625fddc4-c3e9-4899-a16e-b62544f78b20.png)

Подскажите, насколько это нужный пермишн или мы можем его удалить из смерженного манифеста проекта?
Или может планируется его удаление из медиации?

**Comment by mobile-ads-github** [comment]
Добрый день, спасибо за обращение. Добавление пермишена REQUEST_INSTALL_PACKAGES в mobileads-mintegral будет исправлено в следующем релизе адаптера.
Как временно решение, можно удалить использование permission REQUEST_INSTALL_PACKAGES со стороны приложения, через добавление:
`<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" tools:node="remove">`

**Comment by Qhash** [comment]
Спасибо за оперативный ответ!
