### ISSUE TITLE
ANR Executing service my.package/com.yandex.metrica.MetricaService

### ISSUE THREAD

**Issue by DimaKoz** [yandexmobile/yandex-ads-sdk-android#17]
Добрый день. Получил достаточное количество ANR из GooglePlay.
Метрика не используется, идет как обязательная библиотека к нативной рекламе.
build.gradle:
```groovy
compile 'com.yandex.android:mobmetricalib:2.73'
compile 'com.yandex.android:mobileads:2.60'
```
![screen shot 2017-10-19 at 20 37 51](https://user-images.githubusercontent.com/3092276/31785520-110bab7c-b50e-11e7-9a66-dd51ac92910e.png)
Эта проблема присутствует только на Андроид 5.0 и 5.1
<img width="510" alt="screen shot 2017-10-19 at 20 43 11" src="https://user-images.githubusercontent.com/3092276/31785585-48835082-b50e-11e7-856c-74c808b4f5e5.png">
[Лог потоков](https://github.com/yandexmobile/yandex-ads-sdk-android/files/1399462/log3.txt)

**Comment by satsakul** [comment]
Большое спасибо за предоставленную информацию.
Мы завели задачу на исследование данной проблемы и передали информацию разработчикам AppMetrica SDK.

**Comment by alexklints** [comment]
Забираем issue в репозиторий AppMetrica:
https://github.com/yandexmobile/metrica-sdk-android/issues/61
