### ISSUE TITLE
Авто обновление рекламы в  BannerAdView

### ISSUE THREAD

**Issue by tesusov** [yandexmobile/yandex-ads-sdk-android#184]
Здравствуйте! Я только перешёл на использование рекламы от яндекса, но так и не понял почему банер показывает одну и ту же рекламу и не обновляет и если закрыть приложение и открыть заново обновляет. Приложение уже не в тесте и прошло модерацию и размещено в сторе.

**Comment by stayf** [comment]
Аналогичный вопрос у меня. Та же проблема. Рекламу загружает один раз и все. Нужно самому рекламу обновлять по таймеру?

**Comment by tesusov** [comment]
Я оставил заявку в яндекс недели три назад исправляют.

**Comment by Japskiddin** [comment]
На версии mobileads 5,7,0 проблема сохранилась, баннер один раз загрузился, показался и больше не обновляется.

**Comment by SnowVolf** [comment]
Я пока что просто решил это обновлением рекламы в цикле, каждые 15 секунд подгружаю рекламу

**Comment by mobile-ads-github** [comment]
Здравствуйте! Все верно, автообновление рекламных баннеров в SDK сейчас не реализовано. Данный функционал возможно будет имплементирован в следующих версиях

**Comment by stayf** [comment]
@mobile-ads-github это реализовано в версии 6.0?

**Comment by mobile-ads-github** [comment]
Находимся в процессе внедрения.
