### ISSUE TITLE
Media3 support

### ISSUE THREAD

**Issue by Stronger197** [yandexmobile/yandex-ads-sdk-android#185]
Пожалуйста, добавьте `AdsLoader` который поддерживает работу с `media3`

Google уже не раз говорили, что standalone exoplayer будет задепрекейчен. 

В `media3` используется тот же самый `exoplayer 2.18`, отличие лишь в `package`. 
К сожалению возможности изучить ваш код нет, но вероятнее всего доработка для поддержки `media3` состоит лишь в изменении пекеджей у импортов.

Было бы здорово получить поддержку `media3`, ибо на текущий момент для интеграции instream-рекламы в приложение, нужно либо использовать библиотеку, которая будет в ближайшем будущем задепрекейчена, либо делать велосипед через InStream API, хотя уже есть готовое хорошее решение.

**Comment by E-D-W-I-N** [comment]
![image](https://user-images.githubusercontent.com/22594525/219639825-78784ab9-f78a-4298-a978-1350bc7d33d4.png)

**Comment by E-D-W-I-N** [comment]
![image](https://user-images.githubusercontent.com/22594525/219644331-a6d8c174-e1c9-4998-80ba-f372dd408569.png)

**Comment by mobile-ads-github** [comment]
Добрый день, спасибо большое за feature request!
К сожалению в ближайшее время у команды не сможет взять данную задачу в работу.
Как альтернатива, рассмотрите пожалуйста вариант интеграции расширенного InStream API. Данное API не требует зависимости на конкретную версию ExoPlayer, а также позволяет интегрировать рекламные вставки с типом In-Roll и Pause-Roll.
https://yandex.ru/dev/mobile-ads/doc/android/quick-start/instream-advanced.html

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2239. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2239 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by Stronger197** [comment]
Подождем еще полгода... :(

![AQACB_rBp9_0xvGVY942sS8CqVucCdtu8YKpYJacXOxNAs-gEpeDt2EturYJt-hSXunjquPgOmmBEuTD5ohw9vxeLUw](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/21480083/1cee9ab9-6909-4115-9c2f-57725c6a2c0e)

**Comment by mobile-ads-github** [comment]
Спасибо за обращение! На данный момент изучаем возможность миграции на Media3.  Следить за свежими обновлениями можно здесь: https://yandex.ru/adv/news?tag=рекламная%20сеть, или  в телеграмме https://t.me/YANpartner.

**Comment by E-D-W-I-N** [comment]
Подождем ещё полгода 2. От создателей "Подождем ещё полгода... :("
![263991607-1cee9ab9-6909-4115-9c2f-57725c6a2c0e.jpg](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/22594525/b624f273-122d-4cdb-bbe1-ad620e02c058)

**Comment by E-D-W-I-N** [comment]
@mobile-ads-github Добрый день. А можно какой-то комментарий получить по причине закрытия issue? 

Новых release notes не выходило. Будет ли добавлена поддержка Media3?

**Comment by mobile-ads-github** [comment]
Добрый день! Приносим извинения, issue по ошибке закрылся. На данный момент нет никаких новостей о планах по поддержке Media3.

**Comment by mobile-ads-github** [comment]
Добрый день! [Поддержали](https://ads.yandex.com/helpcenter/ru/dev/android/changelog-android#2024) media3 в версии SDK Android 7.5.0.
