### ISSUE TITLE
Not able to add Yandex  to Admob mediation

### ISSUE THREAD

**Issue by maxakash** [yandexmobile/yandex-ads-sdk-android#195]
Hi
 I am trying to add Yandex native ads to my android application via Admob mediation. But while following the documentation (https://yandex.com/dev/mobile-ads/doc/android/adapters/admob-adapter.html), I am getting some errors.

I am not able to import "YandexNative" and "YandexNativeAdAsset" classes and the error I get is 
``` 
Cannot access 'YandexNative': it is internal in 'com.admob.mobileads'
Cannot access 'YandexNativeAdAsset': it is internal in 'com.admob.mobileads.nativeads'
```

The library versions I am using are

```
 implementation 'com.yandex.android:mobileads:5.6.0'
 implementation 'com.yandex.ads.adapter:admob-mobileads:5.6.0.0'
 implementation 'com.google.android.gms:play-services-ads:21.5.0'
```

Please help.

**Comment by beetlea** [comment]
i have too problem, but with library com.yandex
i dont import this library

**Comment by maxakash** [comment]
> Hi, thank you very much for the report. We will fix it in the next release at the end of the week.

Any update on the release?

**Comment by maxakash** [comment]
@mobile-ads-github I am using the library 
 ``` 
        implementation 'com.yandex.ads.adapter:admob-mobileads:5.7.0.0'
        implementation 'com.yandex.android:mobileads:5.7.0'
```

But after using custom event in Admob(following documentation), Yandex adapter is not found in the app. I have correctly used the proguard rules.

Here is the error
![WhatsApp Image 2023-04-02 at 9 56 36 AM](https://user-images.githubusercontent.com/17406944/229331332-5cd7671f-b910-461e-a447-b8d2e8aed311.jpeg)

**Comment by mobile-ads-github** [comment]
Добрый день!

Мы проверили, действительно Ad inspector выдает ошибку интеграции. Это связано с использованием deprecated API в адаптере. Мы исправим это в будущих версиях адаптера. 
Тем не менее, интеграцию можно проверить запустив [Single ad source test](https://developers.google.com/admob/android/ad-inspector#perform_a_single_ad_source_test) — в нем доступен выбор адаптеров Яндекса. 
После теста информация о подборе будет видна в SDK request log в конкретном Ad unit. 

Большое спасибо за подсвеченную проблему!

**Comment by maxakash** [comment]
> Hello!
> 
> We checked whether Ad inspector really gives an integration error. This is due to using of deprecated API in the adapter. We will fix this in future versions . Nevertheless, the adapter works, and the integration can be checked by running a [Single ad source test](https://developers.google.com/admob/android/ad-inspector#perform_a_single_ad_source_test): selection of Yandex adapters is available. After the test, the selection information will be visible in the SDK request log in a specific Ad unit.
> 
> Thanks a lot for the highlighted problem!

Hi,I am running a single ad source test but I am getting all views as null except icon view in the native ad.
