### ISSUE TITLE
ANR Executing service ru.mamba.client/com.yandex.metrica.ConfigurationService

### ISSUE THREAD

**Issue by tihelper** [yandexmobile/yandex-ads-sdk-android#20]
Используем версии библиотек для отображения нативной рекламы:
> compile 'com.yandex.android:mobmetricalib:2.78'
    compile 'com.yandex.android:mobileads:2.62'

Наблюдаем рост ANR отчётов нашего приложения:
<img width="989" alt="2017-12-05 17 52 24" src="https://user-images.githubusercontent.com/5204602/33613230-1fc98070-d9e5-11e7-9fd6-07c6f7d9ca3b.png">

Судя по всему затронуты устройства на Андроид 4.*:
<img width="656" alt="2017-12-05 17 52 28" src="https://user-images.githubusercontent.com/5204602/33613245-2bc3a4a0-d9e5-11e7-903e-3fc8b3a066c7.png">

Отключение инициализации Метрики и отображения нативной рекламы от Яндекса проблему не решает. Наличие зависимостей (компиляция ConfigurationService в Манифест) ведёт к ANR-происшествиям.

[ConfigurationService_issue.txt](https://github.com/yandexmobile/yandex-ads-sdk-android/files/1531640/ConfigurationService_issue.txt)

**Comment by alexklints** [comment]
Привет) А можно стектрейс текстом или файлом, а не скриншотом?

**Comment by tihelper** [comment]
Привет. Обновил стартовый пост: прикрепил текстовый документ с содержимым отчёта.

**Comment by alexklints** [comment]
Перенес issue в репозиторий AppMetrica:
https://github.com/yandexmobile/metrica-sdk-android/issues/60
