### ISSUE TITLE
Banner AdSize.flexibleSize больше чем указывается

### ISSUE THREAD

**Issue by Str4tos** [yandexmobile/yandex-ads-sdk-android#203]
Добрый день.  
Заметили странное поведение Banner Ad используя `com.yandex.android:mobileads:5.6.0`.

Код загрузки рекламы:
```kotlin
val view = BannerAdView(context)
view.setAdUnitId(placement)
val size = AdSize.flexibleSize(320, 50)
view.setAdSize(size)
view.setBannerAdEventListener(this)
view.layoutParams = ViewGroup.LayoutParams(
   size.getWidthInPixels(context),
   size.getHeightInPixels(context)
)
view.loadAd(AdRequest.Builder().build())
```

Хоть и указываем максимальную высоту 50 dp, в итоге видим рекламу больше:

<div>
<img src="https://user-images.githubusercontent.com/22005013/230034305-085c94f5-2d3f-45d4-a917-85bde2c12f9d.png" width="250">
<img src="https://user-images.githubusercontent.com/22005013/230035663-1ab40a49-55d3-4d2e-ab1d-266060a67d98.png" width="250">
</div>

Возможен ли такой баг в Yandex Ads SDK?  

Спасибо за помощь.

**Comment by mobile-ads-github** [comment]
Добрый день! Была проблема на нашей стороне, сейчас исправили. 
Проверьте, пожалуйста, исчезла ли проблема.

**Comment by Str4tos** [comment]
Не удалось повторить
