### ISSUE TITLE
Несовместимость с com.google.dagger:hilt-android:2.45 и com.yandex.android:mobileads:5.7.0

### ISSUE THREAD

**Issue by RinJavDev** [yandexmobile/yandex-ads-sdk-android#205]
Ломается автогенерация кода для `@InstallIn(SingletonComponent::class)`
Получаю такие ошибки компиляции:
```
@ScopeMetadata("javax.inject.Singleton")
 ^
  symbol: class ScopeMetadata
```
  
```
  @QualifierMetadata("dagger.hilt.android.qualifiers.ApplicationContext")
 ^
  symbol: class QualifierMetadata
```

Убираю вашу библиотеку из гредла и проблема исчезает
мой dependencies выглядит так:

```
dependencies {
    //domain from app module
    compileOnly project(path: ':domain')

    //yandex ads
    implementation "com.yandex.android:mobileads:5.7.0"

    //hilt from app modelue
    compileOnly "com.google.dagger:hilt-android:$hilt_version"
    kapt "com.google.dagger:hilt-compiler:$hilt_version"
}
```
Нужно ли мне какие-то дополнительные транзитивные зависимости подтягивать?

**Comment by mobile-ads-github** [comment]
Добрый день, спасибо за обращение. К сожалению не удалось воспроизвести проблему, пришлите пожалуйста пример воспроизведения проблемы на почту mobile-ads-github@yandex-team.ru. Какую версию Hilt вы используете? Попробуйте пожалуйста обновить версию Hilt до последней.
