### ISSUE TITLE
Пустой экран при возврате на полноэкранную рекламу

### ISSUE THREAD

**Issue by DimaKoz** [yandexmobile/yandex-ads-sdk-android#21]
Добрый день.
Обнаружена проблема с полноэкранной рекламой - при возвращении из браузера в приложение, отображается активити полноэкранной рекламы с пустым контентом.
Воспроизводится иногда, гарантированного(100%) воспроизведения добиться не удалось.
Воспроизводилось на устройствах:

- Sony F5121 Android 7.1.1
- HTC Desire 530 Android 6.0.1
- Samsung Galaxy s6 edge SM-G925F Android 6.0.1
- Samsung Galaxy A5 (2016) SM-A510F Android 7.0

build.gradle:

```
compile 'com.yandex.android:mobmetricalib:2.77'
compile 'com.yandex.android:mobileads:2.60'
```
Шаги для воспроизведения:

- Отобразить полноэкранный баннер;
- Кликнуть на него(происходит переход в браузер устройства);
- Вернуться обратно из браузера в приложение хардварной кнопкой назад.

Скриншот:
![screenshot_20171213-151837](https://user-images.githubusercontent.com/3092276/34099163-c7150f02-e3ef-11e7-9ffe-5345322dcac5.png)

**Comment by satsakul** [comment]
Большое спасибо. Завели задачу, в рамках которой будем решать данную проблему. Планируем исправить её в версии мобильной рекламы 2.71

**Comment by satsakul** [comment]
Проблема решена в версии 2.61. Текущая актуальная версия - 2.62.

Большое спасибо за то, что сообщили о проблеме.
