### ISSUE TITLE
AdRequestError: Service temporarily unavailable

### ISSUE THREAD

**Issue by Android355** [yandexmobile/yandex-ads-sdk-android#210]
Добрый день!

C 7 июня 16:00 резко возросло количество ошибок при получении рекламы:

```AdRequestError (code: 1, description: Service temporarily unavailable)```

И сохраняется уже на протяжении двух недель. В чем может быть причина?
Используется SDK последней версии.

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 24764533. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp23.06.2023, 13:24, "Android355" ***@***.***>:
Добрый день!
C 7 июня 16:00 резко возросло количество ошибок при получении рекламы:
AdRequestError (code: 1, description: Service temporarily unavailable)
И сохраняется уже на протяжении двух недель. В чем может быть причина?
Используется SDK последней версии.

**Comment by Android355** [comment]
Проблему решили спустя месяц после ее появления.
