### ISSUE TITLE
ACCESS_WIFI_STATE permission

### ISSUE THREAD

**Issue by vladislav-h** [yandexmobile/yandex-ads-sdk-android#213]
В манифесте com.yandex.android:mobileads вижу, что требуется android.permission.ACCESS_WIFI_STATE . Хочу спросить, обязательно ли оно? Будет ли все правильно работать, если его уберу? Помню, что для mobmetricalib ACCESS_WIFI_STATE не обязательно. Раньше оно не было в манифесте mobileads. Да и вообще, не знаю, чем ACCESS_WIFI_STATE полезно для mobileads (проверить тип соединения можно и имея только android.permission.ACCESS_NETWORK_STATE).

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25044725. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp05.07.2023, 12:31, "vladislav-h" ***@***.***>:
В манифесте com.yandex.android:mobileads вижу, что требуется android.permission.ACCESS_WIFI_STATE . Хочу спросить, обязательно ли оно? Будет ли все правильно работать, если его уберу? Помню, что для mobmetricalib ACCESS_WIFI_STATE не обязательно. Раньше оно не было в манифесте mobileads. Да и вообще, не знаю, чем ACCESS_WIFI_STATE полезно для mobileads (проверить тип соединения можно и имея только android.permission.ACCESS_NETWORK_STATE).

**Comment by mobile-ads-github** [comment]
Здравствуйте! 
Это разрешение не обязательно к указанию.
