### ISSUE TITLE
High crash rate by NullPointerException in 5.9.0 to 6.0.1.0

### ISSUE THREAD

**Issue by caesar-feng** [yandexmobile/yandex-ads-sdk-android#215]
hello
  We have referenced the latest library：
    implementation 'com.yandex.android:mobileads:5.9.0'
    implementation 'com.yandex.ads.adapter:ironsource-mobileads:5.9.0.0'

  but Google has reported frequent NullPointerExceptions.

![image](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/10151825/4911746a-6018-46a5-8603-2957e5326d95)

 Here is the stack trace:
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'android.graphics.Rect android.view.View$AttachInfo.mVisibleInsets' on a null object reference
       at android.view.View.getWindowVisibleDisplayFrame(View.java:14041)
       at com.yandex.mobile.ads.impl.tg1.c(SourceFile:8)
       at com.yandex.mobile.ads.banner.c.j(SourceFile:8)
       at com.yandex.mobile.ads.impl.f71$a.b(SourceFile:44)
       at com.yandex.mobile.ads.impl.gg0.a(SourceFile:28)
       at com.yandex.mobile.ads.impl.gg0$b.handleMessage(SourceFile:73)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:225)
       at android.app.ActivityThread.main(ActivityThread.java:7563)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994

Please help us fix this,Thank you!

**Comment by mobile-ads-github** [comment]
Hello!
Could you please give us a bit more information?
We'd like to know:
- Your IronSource sdk version
- App Id to check possible error logs. 

<details><summary>If you don't want to share them in public, send to our email</summary>
<p>
mobile-ads-github@yandex-team.ru
</p>
</details> 

Thank you for the report

**Comment by mobile-ads-github** [comment]
Hello!
We can't reproduce this crash.
Still waiting extra info, at least your IronSource SDK version for crash check. 

Is there any specific android OS version in crash report?

**Comment by caesar-feng** [comment]
My IronSource sdk version is com.ironsource.sdk:mediationsdk:7.3.1，and i have already sent our app ID to the email address mobile-ads-github@yandex-team.ru on July 7, 2023 at 10:26. Please check your inbox.

-------
Is there any specific android OS version in crash report?

Unfortunately, this crash is occurring across multiple Android versions. Here are detailed screenshots:
![SourceFile - com yandex mobile ads i 1](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/10151825/6dbb5954-13d8-44ec-8407-1c3b0524cefa)
![0 notes](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/10151825/acf0bb2a-2fc5-4cfd-97aa-97fabfa11bc6)

I hope these screenshots will be helpful.

**Comment by mobile-ads-github** [comment]
We checked IS changelog and found following: there is a new version 7.3.1.1 with fixes for custom adapters integration and banners.
https://developers.is.com/ironsource-mobile/android/sdk-change-log/
Could you please update IS sdk version and check?
Thank you!

**Comment by caesar-feng** [comment]
Okay, but this requires us to release a new version and go through a lengthy validation process to ensure that it doesn’t impact existing users before we can restart your SDK.

 If there are any further issues, I will continue to provide updates here.

Additionally, I would like to mention that we have integrated multiple ad mediation platforms, and currently all others are running smoothly.

I suggest you review the code again and ensure the program runs smoothly, at the very least it should not crash.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2235. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2235 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Hi! Is everything working stably now?

**Comment by caesar-feng** [comment]
After disabling the banner ad in the ad platform, everything is running smoothly.

**Comment by caesar-feng** [comment]
![image](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/10151825/7d598c10-f6a5-45ee-926c-a9b629f3efa7)
After upgrading our SDK to 7.3.1.1, today we tried to open the banner ad and the crash occurred again.

Do you have a fix for this issue? Can you tell me in which version it was fixed?

**Comment by caesar-feng** [comment]
Here is the sdk version information which I used:
    //iron source
    api 'com.ironsource.sdk:mediationsdk:7.3.1.1'
    //yandex
    implementation 'com.yandex.android:mobileads:5.10.0'
    implementation 'com.yandex.ads.adapter:ironsource-mobileads:5.10.0.0'

**Comment by caesar-feng** [comment]
![image](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/10151825/e74c8eb1-241a-4f9f-a14a-314da53a26fa)

Crashes still exist in the latest version.

    api 'com.ironsource.sdk:mediationsdk:7.4.0'
    implementation 'com.yandex.ads.adapter:ironsource-mobileads:6.0.1.0'

**Comment by mobile-ads-github** [comment]
Hi caeser-feng! Can you send all the dependencies from the build.gradle?

**Comment by mobile-ads-github** [comment]
Hi caeser-feng! Can you send all the dependencies from the build.gradle?

**Comment by dmitryfisko** [comment]
Hi! The problem will be fixed in the upcoming release.
