### ISSUE TITLE
Ad request completed successfully, but there are no ads available

### ISSUE THREAD

**Issue by whiskyblack** [yandexmobile/yandex-ads-sdk-android#219]
I used sample code with id "demo-banner-yandex" and "demo-interstitial-yandex". They work perfectly. But when I change the ad id I created: "R-M-2550547-4", "R-M-2550547-5" in the sample code, the log always shows: "Ad request completed successfully, but there are no ads available"
How do I fix this?

**Comment by mobile-ads-github** [comment]
Hello! 
Have you updated the package name of the sample app to your original app package name??

**Comment by whiskyblack** [comment]
Yes, I changed the package name but still have the above problem. Could this error be caused by ad id configuration?
I changed the package name as the attached link:
https://drive.google.com/file/d/11BpTAYsH027h8cISywkxA7JSmVNLL9E5/view?usp=sharing

**Comment by mobile-ads-github** [comment]
Hello, now all should be fine. We fixed the issue. Check please.
