### ISSUE TITLE
Возможно ли вручную хендлить click по Native баннеру?

### ISSUE THREAD

**Issue by arturwest** [yandexmobile/yandex-ads-sdk-android#22]

**Comment by satsakul** [comment]
Добрый день. 
Обработку нажатия на компоненты нативной рекламы мы производит внутри SDK. Вам нет необходимости вручную хендлить click по Native баннеру.

Скажите, пожалуйста, а зачем Вы хотите это делать?

**Comment by arturwest** [comment]
@satsakul Добрый день! Спасибо за быстрый ответ. У меня стоит задача реализовать открытие рекламируемого новостного материала внутри приложения, т.к в админке yandex ads у баннера может быть настроен параметр "дополнительный текст" в котором лежит id нужного документа.

**Comment by satsakul** [comment]
Добрый день. Правильно ли я понимаю, что Вы сами формируете кликовую ссылку? Если так, то почему бы в качестве кликовой ссылки не формировать deeplink на свое приложение, содержащий необходимый id документа?

**Comment by arturwest** [comment]
Добрый вечер. Спасибо за совет.
