### ISSUE TITLE
Мерцание банера при автообновлениях рекламы

### ISSUE THREAD

**Issue by stayf** [yandexmobile/yandex-ads-sdk-android#220]
Использую com.yandex.android:mobileads:5.10.0
У меня банер находится в самом верху. И очень часто при автообновлениях этот банер пропадает буквально на 50 мс и потом опять появляется. Из-за этого у меня на эти 50 мс изменяется верстка, что сильно раздражает пользователей. Т.е. получается что банер исчезает полностью с экрана на 50мс. Вы можете сделать так, чтобы не было прыжков размеров банера при автообновлении?

Верстка:

```
BannerAdView ad = ad = new BannerAdView(this);
ad.setAdUnitId("id");
int widthPx = Math.min(Screen.getWidth(), Screen.getHeight());
int widthDp = (int) Screen.pxToDp(widthPx);
ad.setAdSize(AdSize.flexibleSize(widthDp, 56));
mBind.bannerAdViewWrapper.addView(ad);
```

```
<RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <FrameLayout
                android:id="@+id/banner_ad_view_wrapper"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="?attr/colorPrimary">

            </FrameLayout>

            <FrameLayout
                android:id="@+id/fragment_container"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_above="@+id/bottom_navigation"
                android:layout_below="@+id/banner_ad_view_wrapper" />

            <com.google.android.material.bottomnavigation.BottomNavigationView
                android:id="@+id/bottom_navigation"
                android:layout_width="match_parent"
                android:layout_height="48dp"
                android:layout_alignParentBottom="true"
                android:background="?attr/colorPrimary"
                app:elevation="0dp"
                app:itemIconTint="@color/color_bottom_menu_item"
                app:labelVisibilityMode="unlabeled"
                app:menu="@menu/menu_navigation" />

        </RelativeLayout>
```

**Comment by stayf** [comment]
Еще дополню. Т.е. если высота рекламы была 56dp, и меняется на новую рекламу высотой 56dp, то не должно быть никаких промежуточных исчезаний и высоты 0dp.

**Comment by mobile-ads-github** [comment]
Здраствуйте
Мы сейчас готовим новый релиз в котором мы поменяем логику работы с размерами баннера. В новом релизе баннер типа sticky будет всегда возвращать один и тот же размер и вы сможете сразу зафиксировать размеры баннера в вёрстке.
Сейчас, как временное решение, можем предложить обернуть баннер в контейнер фисированного размера и запрашивать баннер с размерами не больше этого контейнера.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2233. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2233 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.
