### ISSUE TITLE
ANR на старте приложения

### ISSUE THREAD

**Issue by yaklimenko** [yandexmobile/yandex-ads-sdk-android#221]
возникают ANR на страте приложения.

ANR возникает в процессе, созданном Yandex.Metrica, являющимся зависимостью библиотеки "Yandex Advertising Network Mobile". Возникает через несколько секунд после старта приложения.

Воспроизводится на версиях 5.4.1 и 5.6.0

[anr-short-log.log](https://github.com/yandexmobile/yandex-ads-sdk-android/files/12160137/anr-short-log.log)
[anr-dumpsys.log](https://github.com/yandexmobile/yandex-ads-sdk-android/files/12160138/anr-dumpsys.log)

```
implementation("com.yandex.android:mobmetricalib:5.3.0")
```
Пробовал

**Comment by mobile-ads-github** [comment]
Здравствуйте 
По логам что вы приложили нельзя понять что именно пошло не так, не могли бы вы скинуть полный дамп потоков во время ANR ?

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2232. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2232 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by yaklimenko** [comment]
сегодня попытаемся воспроизвести и приложить дампы трэдов

**Comment by mobile-ads-github** [comment]
Здравствуйте! Получилось воспроизвести?

**Comment by yaklimenko** [comment]
Сегодня постараемся найти время

**Comment by yaklimenko** [comment]
Пока не выходит. Прошу не закрывать ишью, еще попытаемся

**Comment by mobile-ads-github** [comment]
Окей, будем ждать обратную связь.

**Comment by mobile-ads-github** [comment]
Передадим ваше обращение коллегам из метрики.

**Comment by yaklimenko** [comment]
> Добрый день! Классов рекламного сдк в предоставленных логах нет.

В самом начале же файла threads_report

at com.yandex.metrica.MetricaService.onCreate(SourceFile:2)

Это спустя 15 примерно секунд после запуска приложения... Выполнение всё еще на onCreate

**Comment by mobile-ads-github** [comment]
Это происходит из-за нашей зависимости. Связались с коллегами по поводу причины возникновения этой проблемы.

**Comment by yaklimenko** [comment]
> Это происходит из-за нашей зависимости. Связались с коллегами по поводу причины возникновения этой проблемы.

Может, мне стоит оформить issue  в каком-то другом трекере?

**Comment by mobile-ads-github** [comment]
Указанное устройство - очень древнее и слабое. ANR возникает из-за того, что просто не хватает вычислительных возможностей. Максимум, что можно сделать, это попробовать перенести метричный сервис в основной процесс.

Для этого нужно в AndroidManifest.xml добавить следующее в `application`:

```
<service
            android:name="com.yandex.metrica.MetricaService"
            android:enabled="true"
            android:exported="true"
            tools:remove="android:process" />
```

**Comment by yaklimenko** [comment]
Спасибо. Видимо решение рабочее. Anr перестал беспокоить.
