### ISSUE TITLE
InterstitialAd Android 12 и выше 

### ISSUE THREAD

**Issue by ShamaevDima** [yandexmobile/yandex-ads-sdk-android#222]
На Android 12 и выше происходит утечка памяти при просмотре рекламы. Каждый раз, когда человек посмотрел рекламу, в памяти остается активити. В итоге после нескольких просмотров рекламы у пользователей остается куча экранов в памяти.

**Comment by mobile-ads-github** [comment]
Здравствуйте, какой контекст вы передаёте в АПИ при создание InterstitialAd, контекст активити или приложения ?

**Comment by ShamaevDima** [comment]
Да, я передавал контекст приложения, в этом и была причина. Спасибо!
