### ISSUE TITLE
Я плохо разбираюсь 

### ISSUE THREAD

**Issue by thunderstorms-plus** [yandexmobile/yandex-ads-sdk-android#227]
Можно получить исходники код java без viewbinding?
Пожалуйста 
![Screenshot_20230904_174052_Chrome](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/30003442/1b8f6f72-5413-4c4c-bfa4-e897563690d1)
![Screenshot_20230904_174059_Chrome](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/30003442/0b2449ad-b55d-463b-8638-feb1ff14d050)

**Comment by thunderstorms-plus** [comment]
Хорошо,  жду ответа!=)

**Comment by mobile-ads-github** [comment]
Добрый день, вы можете заменить обращения у `binding` на `(BannerAdView) findViewById(R.id.adView)`.

**Comment by thunderstorms-plus** [comment]
> Добрый день, вы можете заменить обращения к `binding` на `(BannerAdView) findViewById(R.id.adView)`.

Спасибо большое за ответ!=)
