### ISSUE TITLE
Rewarded ad not working

### ISSUE THREAD

**Issue by abrihamdemisse** [yandexmobile/yandex-ads-sdk-android#229]
after loading rewaeded ad, and trying to show ,  on dismissed called instantly and nothing shown.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2313. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2313 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Hi! Is everything working stably now?

**Comment by abrihamdemisse** [comment]
> Hi! Is everything working stably now?

nope 👎
