### ISSUE TITLE
Когда будет либа для windows 10 mobile?

### ISSUE THREAD

**Issue by alexeygritsenko** [yandexmobile/yandex-ads-sdk-android#23]
Сорян если не по адресу, просто блин что за несправедливость? UWP приложения тоже хотят вашей монетезации!

**Comment by satsakul** [comment]
Добрый день! Спасибо за обращение.
В ближайшее время мы не планируем разрабатывать SDK для UWP приложений. 
Если такие планы появятся, мы обязательно сообщим Вам об этом.
