### ISSUE TITLE
Почему нет примеров на java?

### ISSUE THREAD

**Issue by sermyagin** [yandexmobile/yandex-ads-sdk-android#231]
Почему нет примеров на java? не могу внедрить много ошибок.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2354. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2354 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by xheatcodes** [comment]
Примеров нет. Да в джаву переписать не составит труда, но ошибок с ресурсами очень много. Сидишь гадаешь с версиями плагинов. Одно лечиться второе ломается. Очень удобно))

**Comment by sermyagin** [comment]
Пробовал перейти на 6 не смог много ошибок и требует api 33-34 что несовместимо с моим приложением. Остался на 5.10.0.

**Comment by xheatcodes** [comment]
получилось но все же времени ушло часа 3))

**Comment by xheatcodes** [comment]
у меня на 33 в итоге на 34 ошибки выдавало и с com.google.android.material:material:1.7.0 вышло)

**Comment by mobile-ads-github** [comment]
Добрый день, в новой документации есть примеры как на Java так и на Kotlin https://yandex.ru/support2/mobile-ads/ru/dev/android/quick-start
