### ISSUE TITLE
com.yandex.android:mobmetricalib:5.3.0 depricated

### ISSUE THREAD

**Issue by stayf** [yandexmobile/yandex-ads-sdk-android#232]
Добрый день. Использую com.yandex.android:mobileads:6.0.1
И юзаю appmetrica для трекинга установок. Мигрировал на новую аналитику io.appmetrica.analytics:analytics:6.0.0
Но как я понимаю, у вас в com.yandex.android:mobileads:6.0.1 используется com.yandex.android:mobmetricalib:5.0.0 из-за чего у меня увеличился размер apk на 0,5 мб. Просьба мигрировать на io.appmetrica.analytics:analytics:6.0.0 в следующем релизе.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2369. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2369 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день, в одном из ближайших релизов уже планируется сделать это

**Comment by OlegTarashkevich** [comment]
Добрый день, @mobile-ads-github 
А могли бы Вы просто удалить appmetrica из рекламной sdk?

**Comment by mobile-ads-github** [comment]
Здравствуйте! На данный момент мы не готовы полностью отказаться от использования Appmetrica, т.к используем её для сбора аналитики.

**Comment by OlegTarashkevich** [comment]
@mobile-ads-github Благодарю за ответ.
Ничего страшного, можно оставлять Appmetrica. Мы приняли решение отказаться от Yandex в пользу Applovin и Appodeal.
