### ISSUE TITLE
RewardedAdEventListener

### ISSUE THREAD

**Issue by farves** [yandexmobile/yandex-ads-sdk-android#233]
Здравствуйте! При ошибке загрузки RewardedAD, в RewardedAdEventListener условие не выполняется в функции onAdFailedToShow, например: 
override fun onAdFailedToShow(adError: AdError) {
            	Toast.makeText(this, "RewardedAD: AdError", Toast.LENGTH_LONG).show()
            }
сборка 6.0.1

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2385. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2385 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день! onAdFailedToShow(adError: AdError) - вызывается при ошибках показа. При ошибках загрузки должен вызываться onAdFailedToLoad
