### ISSUE TITLE
Crashes occur when using version 6.0.0

### ISSUE THREAD

**Issue by Oyama-Oyama** [yandexmobile/yandex-ads-sdk-android#234]
![57EDEFBB-C9C5-44e8-855C-A8D810ACC203](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/17978212/0cf6245c-7c5f-42b0-8e97-5941c579adf5)
Errors are reported randomly, but frequently

**Comment by Oyama-Oyama** [comment]
Frequently seen on rewarded video ads

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2402. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2402 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by Oyama-Oyama** [comment]
any update?

**Comment by mobile-ads-github** [comment]
Good day! 
We apologise for the long wait, we are currently still working on solving your problem.

**Comment by mobile-ads-github** [comment]
Hi! Sorry for the long answer. We have solved the problem. You need to add ProGuard-rules:
```
-keep class com.yandex.div.** { *; }
-keep class com.yandex.div2.** { *; }
```

**Comment by Oyama-Oyama** [comment]
![截屏2023-12-14 11 06 32](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/17978212/e4fbbefd-85cc-450d-a429-f07289662da5)
It doesn't solve this problem! Is casting DivLinearLayoutManager to DivGridLayoutManager the wrong action here?

**Comment by Oyama-Oyama** [comment]
![截屏2023-12-14 11 09 50](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/17978212/ba39f499-2bfa-4e17-87bc-ec3fcee40a51)
![截屏2023-12-14 11 10 10](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/17978212/dd3822f1-1869-4fd3-9796-9017d14e6054)

**Comment by Oyama-Oyama** [comment]
We look forward to hearing from you

**Comment by jsding** [comment]
Same issue, we need to remove yandex mobile ads from the waterfall to resolve crashes.
