### ISSUE TITLE
Баннер. Не правильно расчитывается размер текста.

### ISSUE THREAD

**Issue by stayf** [yandexmobile/yandex-ads-sdk-android#235]
![Screenshot_1](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/1859216/a04e1db0-ebac-494f-ab4e-992053d89baf)
Не всегда корректно расчитывается размер рекламного текст. У меня баннер в шапке. InlineSize. Версия sdk 6.0

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2421. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2421 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Здравствуйте! Пришлите пожалуйста на почту mobile-ads-github@yandex-team.ru ID блока который вы используете для запроса этой рекламы.  В теме письма укажите пожалуйста: "GitHub: Баннер. Не правильно расчитывается размер текста. #235"
