### ISSUE TITLE
Ad request completed successfully, but there are no ads available

### ISSUE THREAD

**Issue by Drzeww** [yandexmobile/yandex-ads-sdk-android#238]
Hello.
From 28 June in every created new ad unit i have an issue with adview problem, firstly i thought its some SDK
issue and it will be fixed in update, but nothing changed from that time.
The AD appearing 2-3 times then getting locked with error :
"[Integration] Ad request completed successfully, but there are no ads available."
Its highly hurts my ECPM which decreased from 1.50$ to 0,30-0,40$

The test ads works perfectly and have 100% fill rate.
Even on demo build with official yandex source code the error steal apeearing after 2 ads on my YANDEX UNITS.

https://drive.google.com/file/d/1sFjgiR3vKPRxTeP6kzIus35yIc_UIFEL/view?usp=sharing

Version of SDK 6.0.1 + Yandex metrica 5.3.0

AD UNITS :

Banner :         R-M-2565486-1
Interstitial :    R-M-2565486-2

I'm also attach the charles record : 

https://drive.google.com/file/d/1ta3nWnHNrt3ZfXRH4eZThmu46p9rzxmh/view?usp=sharing

**Comment by mobile-ads-github** [comment]
Hello! This is a normal situation when there is no suitable advertising for your ad request. 
Unfortunately, your application has been removed from Google Play, so we have closed the issue.
