### ISSUE TITLE
Service temporarily unavailable. For adUnitId = "demo-native-content-yandex"

### ISSUE THREAD

**Issue by SamGitH** [yandexmobile/yandex-ads-sdk-android#240]
Здравствуйте, тестирую запрос для нескольких нативных реклам (NativeBulkAdLoader)

`val adRequestConfiguration = NativeAdRequestConfiguration.Builder("demo-native-content-yandex").build()`

Но приходит ошибка:
`AdRequestError (code: 1, description: Service temporarily unavailable. Please try again later., adUnitId: null)`

Проблема в adUnitId?  Пробовал еще: demo-native-app-yandex и demo-native-video-yandex. Тоже не работают, все такая же ошибка. Может еще какой то есть adUnitId? Но в документации больше не нашел.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2551. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2551 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by SamGitH** [comment]
> Здравствуйте! Проверьте пожалуйста, сейчас все должно быть в порядке.

Нет, ошибка все та же. Работает только если создать профиль в "Яндексе рекламная сеть" и получить уже там личный adUnitId.

**Comment by mobile-ads-github** [comment]
Здравствуйте! Дело в том, что на текущий момент демо-блоки не предназначены для использования в запросах с несколькими рекламами. Вы можете указать количество реклам для загрузки равное 1, тогда запрос будет успешен. Для запроса же более 1 рекламы используйте личные adUnitId.
