### ISSUE TITLE
unity-ads:4.9.0 contains an issue that affects optimal ad delivery

### ISSUE THREAD

**Issue by SergeyA** [yandexmobile/yandex-ads-sdk-android#242]
Подключил к приложению свежую версию SDK:
```
implementation "com.yandex.android:mobileads:6.1.0"
implementation "com.yandex.android:mobileads-mediation:6.1.0.0"
```

После релиза приложения получил предупреждение от Google Play:

> Последний рабочий выпуск содержит SDK с критическими ошибками
> com.unity3d.ads:unity-ads:4.9.0
> К этой версии SDK приложено сообщение от разработчика:
> SDK 4.9.0 contains an issue that affects optimal ad delivery in some scenarios. Please update to the next version (4.9.1 or higher), or related Mediation adapter, as soon as it is available.
> С 15 февраля 2024 г. 00:00 (по UTC) вы не сможете публиковать новые версии приложения, в которых используется этот SDK.

Для исправления пришлось временно подключить новую версию unity-ads вручную 
```
implementation 'com.unity3d.ads:unity-ads:4.9.1'
```

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2663. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2663 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.
