### ISSUE TITLE
Нужно отключение метрики когда отключена реклама

### ISSUE THREAD

**Issue by XJIOP** [yandexmobile/yandex-ads-sdk-android#243]
Как отключить метрику? В приложении есть покупка премиум для отключения рекламы, рекламу отключаю а метрика висит со своим сервисом...

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2682. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2682 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Здравствуйте! На данный момент в библиотеке нет API для полного отключения функционала SDK.
