### ISSUE TITLE
Плохое качество картинок в баннерах AdFox в т.ч. в sample

### ISSUE THREAD

**Issue by Zozulinsky** [yandexmobile/yandex-ads-sdk-android#244]
Добрый день! При показе баннера adfox ухудшается качество картинки. Проблема возникает только на Android, на iOS все ок.
На скриншоте верхняя картинка получена по ссылке, которая прилетает в sdk (https://avatars.mds.yandex.net/get-adfox-content/2462621/211029_adfox_1710443_4638781_2.c0b4e7a1843d67552d8f21f5b2aa40d5.jpg/optimize.webp),
а нижняя картинка - это итоговый баннер.
 
<img width="349" alt="image" src="https://github.com/yandexmobile/yandex-ads-sdk-android/assets/13776823/d3d96cd7-9797-4eef-bbd3-11c92b34ec7a">

**Comment by art-ylem** [comment]
same problem!

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2695. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2695 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день, приношу извинения за долгий ответ! Это особенность работы SDK на Андроид. Чтобы предотвратить сжатие исходного изображения - необходимо, чтобы разрешение в AdFox соответствовало нативному разрешению изображения.
