### ISSUE TITLE
OnAdFailedToLoad

### ISSUE THREAD

**Issue by ShayCormac2062** [yandexmobile/yandex-ads-sdk-android#246]
Делаю мобильное приложение, но при запросе "App Open Ad" пишет: "ad request completed successfully. but there are no ads available", демо-реклама работает, я неправильно настроил рекламу или что то сделал не так?

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2751. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2751 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Здравствуйте! Вы вызываете рекламу в landscape-ориентации?

**Comment by ShayCormac2062** [comment]
Здравствуйте. Нет, она у меня открывается в portrait-ориентации

**Comment by Drzeww** [comment]
Have the same issue, i am not able to monetize my apps because that error

**Comment by mobile-ads-github** [comment]
Здравствуйте! Это возможное поведение. Мы не можем гарантировать 100% fill rate.  Если при тестировании на демо-блоке реклама подбирается, значит блок интегрирован корректно.

**Comment by mobile-ads-github** [comment]
> Have the same issue, i am not able to monetize my apps because that error

Hello! This is normal behavior. We do not guarantee a 100% fill rate. If advertising is selected during testing on a demo block, it means that the block is integrated correctly.
