### ISSUE TITLE
Утечка памяти в InterstitialAd (mobileads:6.3.0)

### ISSUE THREAD

**Issue by FASius** [yandexmobile/yandex-ads-sdk-android#249]
Использую версию SDK 6.3.0, столкнулся с утечкой памяти после закрытия Interstitial рекламы от Яндекса. В памяти остаются классы AdActivity и ReportFragment. Проблема воспроизводится в [YandexMobileAdsExample](https://github.com/yandexmobile/yandex-ads-sdk-android/tree/master/YandexMobileAdsExample). Для поиска утечек использовался встроенный в Android Studio profiler

![image](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/71797340/4be0bdfe-0410-4207-b239-5ee0d2aa1d8f)

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2849. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2849 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день! Изучаем ситуацию. Вернемся с результатом.

**Comment by mobile-ads-github** [comment]
Еще раз приветствуем! Действительно, обнаружили проблему на своей стороне, спасибо за обращение! Исправим в ближайшем релизе.
