### ISSUE TITLE
Утечка памяти не исправлена в 6.4.0

### ISSUE THREAD

**Issue by vellrya** [yandexmobile/yandex-ads-sdk-android#251]
Здравствуйте.

Issue [249](https://github.com/yandexmobile/yandex-ads-sdk-android/issues/249) закрыта, однако проблема воспроизводится в новой версии 6.4.0.

В собственном рекламном Activity использую рекомендованный метод onDestroy:
```
    override fun onDestroy() {
        rewardedAdLoader?.setAdLoadListener(null)
        rewardedAdLoader = null
        rewardedAd?.setAdEventListener(null)
        rewardedAd = null

        super.onDestroy()
    }
```

LeakCanary сообщает об утечке в 100% случаев, как для демо-блока Interstital, так и для Rewarded
Стоит ли рассчитывать на исправление ошибки в ближайшее время, или пока остаться на 5.10.0?
Прикладываю отчет LeakCanary:
[LeakReport.txt](https://github.com/yandexmobile/yandex-ads-sdk-android/files/14264610/LeakReport.txt)

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2929. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2929 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.
