### ISSUE TITLE
Crash at the detector com.yandex.mobileads.lint.appmetrica.AppMetricaIntervalVersionDetector

### ISSUE THREAD

**Issue by sboishtyan** [yandexmobile/yandex-ads-sdk-android#252]
📚 Mobile ads version
6.0.1

📝 Description
I ran lint on our project and got
Gradle 8.5
Kotlin 1.9.22
AGP 8.2.2
lint 31.2.2

Error: Unexpected failure during lint analysis (this is a bug in lint or one of the libraries it depends on)

Message: Cannot invoke "com.android.ide.common.repository.GradleCoordinate.getVersion()" because "gradleDependency" is null

The crash seems to involve the detector com.yandex.mobileads.lint.appmetrica.AppMetricaIntervalVersionDetector.
You can try disabling it with something like this:
    android {
        lint {
            disable "AppMetricaSdkVersion"
        }
    }

Error: Unexpected failure during lint analysis (this is a bug in lint or one of the libraries it depends on)

Message: Cannot invoke "com.android.ide.common.repository.GradleCoordinate.getVersion()" because "gradleDependency" is null

The crash seems to involve the detector com.yandex.mobileads.lint.appmetrica.AppMetricaIntervalVersionDetector.
You can try disabling it with something like this:
    android {
        lint {
            disable "AppMetricaSdkVersion"
        }

**Comment by mobile-ads-github** [comment]
Hi! This issue has been fixed in 6.4.0. You can upgrade.
