### ISSUE TITLE
Невозможно переиспользовать адаптивный sticky-баннер между разными Activity

### ISSUE THREAD

**Issue by subprogram** [yandexmobile/yandex-ads-sdk-android#253]
У меня приложение, в котором пользователь может быстро переходить между экранами и поэтому нет смысла в каждой отдельной активити создавать новый баннер и делать новый запрос рекламы. Я переиспользую один и тот же баннер на разных активити. 
С баннерами AdMob и AppLovin никаких проблем при таком подходе не возникает. В версии SDK 5.10.0 тоже все более менее работает нормально. Хотел обновиться до версии 6.4.0, но столкнулся с проблемой - не всегда, но очень часто при переходе между экранами от баннера остается только зеленая рамка. В логах при этом никаких проблем не обозначается.
Можно ли вернуть возможность переиспользования баннера в новой версии SDK?

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2943. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2943 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by subprogram** [comment]
> Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2943. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

В течение 2 дней никто не вернулся с ответом. Уже больше 3 недель тишина...

**Comment by mobile-ads-github** [comment]
Добрый день! Извиняемся за долго ожидание! Можете приложить скринкаст проблемы. Не смогли воспроизвести на своей стороне.

**Comment by subprogram** [comment]
Добрый день! Прикладываю видео с воспроизведением проблемы.
https://github.com/yandexmobile/yandex-ads-sdk-android/assets/9901443/c50d9005-36a9-4344-8d57-226d722e280e

**Comment by mobile-ads-github** [comment]
При подобной проблеме после смены ориентации экрана и вызова loadBannerAd()  что возвращает setBannerAdEventListener()?

**Comment by subprogram** [comment]
2024-03-18 18:33:56.195 30125-30125 onAdLoaded
2024-03-18 18:33:58.588 30125-30125 onImpression 

<Баннер отображается>
<Повернул экран>

2024-03-18 18:34:10.254 30125-30125 onAdLoaded
2024-03-18 18:34:12.708 30125-30125 onImpression 

<Баннер отображается>
<Повернул экран>

2024-03-18 18:34:18.840 30125-30125 onAdLoaded

<Вместо баннера зеленая рамка>

**Comment by mobile-ads-github** [comment]
Спасибо за уточнение! Передали команде разработки для разбора ситуации

**Comment by mobile-ads-github** [comment]
Добрый день! Исправили в последнем релизе
