### ISSUE TITLE
Missing class com.yandex.metrica.ModulesFacade

### ISSUE THREAD

**Issue by nemosofts** [yandexmobile/yandex-ads-sdk-android#254]
Missing class com.yandex.metrica.ModulesFacade (referenced from: void com.yandex.varioqub.appmetricaadapter.appmetrica.Mobmetricalib.reportVarioqubData(java.lang.String, byte[]))

![Screenshot_2](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/60071276/2deea43f-60c7-4f0c-af61-833b6274e1f9)

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2963. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2963 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by nemosofts** [comment]
-dontwarn com.yandex.metrica.**

![Screenshot_4](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/60071276/a9fbcc45-dd48-4256-bab3-24222e735319)
