### ISSUE TITLE
Межстраничная реклама грузится, но показывает белый экран.

### ISSUE THREAD

**Issue by ckozlogop** [yandexmobile/yandex-ads-sdk-android#255]
![Screenshot_20240307-174141](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/140646854/6a3b1554-e099-4241-bf36-2af6b4f595f9)
Добрый день!
Подскажите, почему реклама частенько (но не всегда) отображается так как на скриншоте? Демо блоки грузятся без проблем. Реклама по умному водопаду от my target грузится без проблем.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3021. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3021 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день! Пришлите, пожалуйста, на почту mobile-ads-github@yandex-team.ru AdUnitId блока по которому вы запрашиваете рекламу. В теме письма укажите: Межстраничная реклама грузится, но показывает белый экран. #255
