### ISSUE TITLE
Утечка памяти в Interstitial and Rewarded (mobileads:6.4.1)

### ISSUE THREAD

**Issue by FASius** [yandexmobile/yandex-ads-sdk-android#258]
Привет!

Проблема которая наблюдалась в https://github.com/yandexmobile/yandex-ads-sdk-android/issues/249 осталась в версии 6.4.1. Её также можно воспроизвести в Sample. 

Есть какая-нибудь информация по задаче? Может быть её можно пофиксить на стороне приложения?

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3076. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3076 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by alexmedv** [comment]
Зашел, чтоб зарепортить аналогичную проблему, а тут уже все давно в курсе оказывается. Поторопитесь пожалуйста 🙏

**Comment by mobile-ads-github** [comment]
Добрый день! Спасибо за ожидание. Проблему исправили в 7.0.0. Рекомендуем обновиться.

**Comment by vesnagames** [comment]
Всем привет
@alexmedv @FASius, подскажите, удалось решить проблему с апдейтом на 7.0.0.?
Судя по всему в 7.0.1. та же проблема с утечками после закрытия интеров.

**Comment by alexmedv** [comment]
@vesnagames Тестировал версию 7.0.0 – утечек не видел
