### ISSUE TITLE
Сan't deliver broadcast

### ISSUE THREAD

**Issue by SamGitH** [yandexmobile/yandex-ads-sdk-android#266]
Публикую в Google play store приложение и при модерации возникает ошибка, которую мне самому не удалось отловить, но судя по видеозаписи приложенной Google модерацией ошибка возникает при использовании функции подачи жалобы через значок меню в нативной рекламе (я использую нативную рекламу со своим ключом РСЯ и пока приложение находится в тестовом режиме, там соответственно отображается тестовая реклама Яндекс Недвижимость).
Вот лог ошибки:
`Exception android.app.RemoteServiceException$CannotDeliverBroadcastException: can't deliver broadcast
  at android.app.ActivityThread.throwRemoteServiceException (ActivityThread.java:1980)
  at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2242)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at android.app.ActivityThread.main (ActivityThread.java:7898)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:936)`

Вот здесь это происходит (судя видеозаписи приложенной Google модерацией ошибка возникает при нажатии на кнопку "проблемы с картинкой"):
![Screenshot_20240507_134837](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/22810347/14cb0d4d-b508-4294-903c-ca9f4c77da8b)

Я не использую в своем приложении Broadcast и сторонних библиотек, которые могли бы использовать Broadcast.

Вопрос, используете ли вы Broadcast в com.yandex.android:mobileads:7.0.1? Если да, то не могли бы вы пофиксить этот баг.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3222. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3222 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день! Можете попытаться пройтись по следующим шагам для решения проблемы? 
https://stackoverflow.com/questions/72902856/cannotdeliverbroadcastexception-only-on-pixel-devices-running-android-12
https://stackoverflow.com/questions/76340386/fatal-exception-android-app-remoteserviceexception-cant-deliver-broadcast
https://stackoverflow.com/questions/46971153/fatal-exception-android-app-remoteserviceexception-cant-deliver-broadcast-at
https://stackoverflow.com/questions/48804456/how-to-fix-android-app-remoteserviceexception-without-any-message-not-related
Мы полагаем, что проблема на стороне Android https://issuetracker.google.com/issues/245258072?pli=1.
