### ISSUE TITLE
Лишние правила proguard в медиация mintegral

### ISSUE THREAD

**Issue by 111970Loki** [yandexmobile/yandex-ads-sdk-android#267]
Правила находящиеся в [mobileads-mintegral-16.6.61.0.aar](https://repo.maven.apache.org/maven2/com/yandex/ads/mediation/mobileads-mintegral/16.6.61.0/mobileads-mintegral-16.6.61.0.aar)
содержат в себе лишние правила:
-keep interface androidx.** { *; }
-keep class androidx.** { *; }
-keep public class * extends androidx.** { *; }

тогда как сам минтеграл рекомендует - https://github.com/Mintegral-official/mediation-android/blob/master/mediation/proguard-rules.pro
а также
    -keepattributes Signature   
    -keepattributes *Annotation*   
    -keep class com.mintegral.** {*; }  
    -keep interface com.mintegral.** {*; }  
    -keep class android.support.v4.** { *; }  
    -dontwarn com.mintegral.**   
    -keep class **.R$* { public static final int mintegral*; }
    -keep class com.alphab.** {*; }
    -keep interface com.alphab.** {*; }

Эти правили мб и упрощают жизнь вашим разработчикам, но ломают обфускацию моего приложения - видны все поля и методы фрагментов, активити и тд
Зачем они туда были добавлены не очень понятно, в том же майтаргете их нет

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3231. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3231 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by 111970Loki** [comment]
правил с сдк минтеграла, для исключения ваших правил использую:
afterEvaluate {
    tasks.findAll { task -> task.name.startsWith('minify') }.each { task ->
        task.configure {
            configurationFiles.from.collect().each { fileCollection ->
                if (fileCollection instanceof FileCollection) {
                    configurationFiles.from.remove fileCollection
                    configurationFiles.from.add fileCollection.filter { file ->
                        !file.path.contains("mobileads-mintegral")
                    }
                }
            }
        }
    }
}

межстраничка и баннеры показываются

**Comment by mobile-ads-github** [comment]
Добрый день! Передали информацию в команду разработки. Вернемся с ответом  в ближайшее время.

**Comment by mobile-ads-github** [comment]
Добрый день! Пофиксили в последнем релизе
