### ISSUE TITLE
Миграции для поддержки AGP 8.x

### ISSUE THREAD

**Issue by vanyasem** [yandexmobile/yandex-ads-sdk-android#269]
Начиная с версии AGP (Android Gradle Plugin) 8 SDK больше не собирается с ошибкой:
```
com.android.builder.errors.EvalIssueException: Namespace not specified.
Specify a namespace in the module's build file: yandex_mobileads-7.1.0/android/build.gradle.
See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
```

Описание необходимой миграции находится здесь: https://github.com/react-native-community/discussions-and-proposals/issues/671

Относится к https://github.com/yandexmobile/yandex-ads-flutter-plugin/issues/36

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3333. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3333 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.
