### ISSUE TITLE
Черный экран вместо рекламы SDK 2.62 Android 4.1.2

### ISSUE THREAD

**Issue by RedboxSoft** [yandexmobile/yandex-ads-sdk-android#28]
Устройство Motorola Droid  Bionik.
В разные периоды времени с разной частотой (порой более 50% показов) наблюдается непрогруженная реклама. Выглядит это так:

https://ibb.co/dMr2ho
https://ibb.co/jVSxF8

То же самое и на последней версии SDK 2.72

**Comment by satsakul** [comment]
Добрый день. Не могли бы Вы сообщить название Вашего приложения?
Проблема воспроизводится только на Motorola Droid Bionik?

**Comment by RedboxSoft** [comment]
Вот приложение: https://play.google.com/store/apps/details?id=com.justanothertry.slovavk

Для тестирования я использую Motorola Droid Bionik и Motorola Moto X (1 gen.) на Android 5.1
На Moto X такого ни разу вроде бы не видел, а на Motorola Droid Bionik воспроизводится достаточно часто, что дает основание предполагать что это специфическая для Android 4 проблема. Насчет других устройств у меня информации нет.

P.S. Привет, Стас :)

**Comment by satsakul** [comment]
Привет :)
На данный момент нам не удаётся воспроизвести проблему. 
Если у Вас проблема воспроизводится стабильно на этом девайсе, быть может Вы можете прислать сессию сниффера?

**Comment by RedboxSoft** [comment]
Пытался пару дней воспроизвести проблему, тоже не получается. Учитывая тот факт, что в приложении ничего не менялось могу предположить, что проблема связана с каким-то определенным баннером или типом банера, может рекламодатель заливает какую-то битую картинку или специфический текс/ссылку добавляет. В общем буду наблюдать дальше, если опять словлю такое поведение, то запишу сессию сниффера.

**Comment by satsakul** [comment]
Большое спасибо :)

**Comment by nikitoSha** [comment]
У наших пользователей такое тоже проявляется, мобилы. например, Galaxy S3 :)
