### ISSUE TITLE
Флаг AUTOMATIC_SDK_INITIALIZATION не совсем ожидаемо работает

### ISSUE THREAD

**Issue by drusak** [yandexmobile/yandex-ads-sdk-android#281]
Подскажите, Выставляю в манифесте
```
<meta-data
            android:name="com.yandex.mobile.ads.AUTOMATIC_SDK_INITIALIZATION"
            android:value="false" />
```
Но в логах все равно видно что какие-то проверки яндекс идут.
```
YandexAds  E  [Integration] MISSING ADAPTERS: Banner, Interstitial, Rewarded
YandexAds  E  [Integration] AdColony: NOT INTEGRATED
YandexAds  E  [Integration] MISSING ADAPTERS: Banner, Interstitial, Rewarded
YandexAds  E  [Integration] AppLovin: NOT INTEGRATED
...
```
Ожидалось, что реклама ничего не будет делать до явного вызова `initialize()`
Этот флаг не работает, или причина логов другая?

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3721. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3721 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день! Это ожидаемое поведение. Проверка интеграции адаптеров происходит в любом случае. Флаг работает.
