### ISSUE TITLE
Interstitial рекламу можно закрыть кнопкой/жестом "Назад"

### ISSUE THREAD

**Issue by DaniilPavlenko** [yandexmobile/yandex-ads-sdk-android#289]
**Версия SDK: 7.6.0**

Рекламу можно закрыть, при включенной поддержке "[Predictive Back Gesture](https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture)".

### Шаги воспроизведения
1. В `AndroidManifest.xml` приложения установить `android:enableOnBackInvokedCallback="true"`.
```xml
...
<application
    android:enableOnBackInvokedCallback="true"
...
```
2. Запустить Interstitial рекламу.
3. Как только показалась Interstitial реклама, использовать кнопку/жест "Назад".

### Фактический результат
Реклама закрывается.

<details>
<summary>▶️ Запись экрана</summary>

[interstitial-actual.webm](https://github.com/user-attachments/assets/ee69bf9d-3c85-47dd-9436-4804711c34e3)  

</details>

### Ожидаемый результат
Реклама не закрывается без нажатия спец. кнопок, появляющихся после таймаута.

<details>
<summary>▶️ Запись экрана</summary>

[interstitial-expected.webm](https://github.com/user-attachments/assets/b859800d-271c-42a3-b467-207019bf6405)

</details>

Воспроизводится на устройствах:
* Android 15 (Emulator - Pixel 8a)
* Android 14 (Реальный девайс - Realme GT6)

### Костыль, которым удалось это полечить (?)
Переопределил `com.yandex.mobile.ads.common.AdActivity` в `AndroidManifest.xml` приложения и задал `android:enableOnBackInvokedCallback="false"`, но не знаю, как это сработает с другими провайдерами рекламы.

```xml
<application>
    <activity
        android:name="com.yandex.mobile.ads.common.AdActivity"
        android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
        android:enableOnBackInvokedCallback="false"
        android:theme="@style/MonetizationAdsInternal.AdActivity" />
...

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3926. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3926 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by DaniilPavlenko** [comment]
Нашёл [более подходящее решение](https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture#opt-activity-level) на данный момент (вместо переопределения Activity из SDK).
1. Отключить "Predictive back gesture" глобально для приложения.
```xml
<application android:enableOnBackInvokedCallback="false" />
```

2. Включить его только для собственных Activity в приложении.
```xml
<activity android:enableOnBackInvokedCallback="true" />
```
