### ISSUE TITLE
android.database.sqlite.SQLiteException

### ISSUE THREAD

**Issue by nikitoSha** [yandexmobile/yandex-ads-sdk-android#29]
Доброго времени суток.
У 30% пользователей падает приложение. Ниже стек из "ANR и сбои":

> android.database.sqlite.SQLiteException:  
  at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount (Native Method) 
  at android.database.sqlite.SQLiteConnection.executeForChangedRowCount (SQLiteConnection.java:732) 
  at android.database.sqlite.SQLiteSession.executeForChangedRowCount (SQLiteSession.java:754) 
  at android.database.sqlite.SQLiteStatement.executeUpdateDelete (SQLiteStatement.java:64) 
  at android.database.sqlite.SQLiteDatabase.executeSql (SQLiteDatabase.java:1676) 
  at android.database.sqlite.SQLiteDatabase.execSQL (SQLiteDatabase.java:1605) 
  at org.chromium.android_webview.HttpAuthDatabase$1.run (HttpAuthDatabase.java:19)

Инструмент разработчика установлен корректно, по справке. Яндекс метрика в классе приложения не инициализируется, а работает только как вспомогательная библиотека.
Приложение поддерживает Андроид от 4.1 до 8.1

**Comment by nikitoSha** [comment]
Поставил mobileads:2.72 вместо 2.71. Посмотрим, может вылечит.

**Comment by satsakul** [comment]
Добрый день. Не могли бы Вы предоставить более полные стектрейсы/логи. По приведенному выше стеку сложно понять на чьей стороне проблема.

**Comment by nikitoSha** [comment]
@satsakul , к сожалению, это всё, что мне сказал гугл. Я бы и сам не прочь посмотреть, в каком именно классе вываливается. То, что я вижу в консоли:
![2018-06-11 17 50 25](https://user-images.githubusercontent.com/15741303/41227742-19de9a20-6da0-11e8-8c85-2017b416b778.png)

Версия Метрики - 3.0.0

    compile 'com.yandex.android:mobmetricalib:3.0.0'
    compile 'com.yandex.android:mobileads:2.72'

Не хотел нагружать приложение сервисами, типа CrystalReport и подключением метрики, но, наверно, придется попытаться поймать метрикой исключение

**Comment by nikitoSha** [comment]
На моей стороне не подключается sqlite. Подключенные сторонние библиотеки так же не используют эту СУБД. В общем, гадать можно долго, конечно, но буду подключать отчеты метрики, чтобы больше данных было

**Comment by nikitoSha** [comment]
Здравствуйте.
Эта ошибка всё никак не оставляет в покое наших пользователей. Лог из яндекс-метрики:

`android.database.sqlite.SQLiteException: table httpauth already exists (code 1) ################################################################# Error Code : 1 (SQLITE_ERROR) Caused By : SQL(query) error or missing database. (table httpauth already exists (code 1)) ################################################################# at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method) at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:878) at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754) at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64) at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1814) at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1743) at org.chromium.android_webview.HttpAuthDatabase$1.run(HttpAuthDatabase.java:1132)`

**Comment by nikitoSha** [comment]
@satsakul есть какое-нибудь решение проблемы? Получается, что пытается создать таблицу "httpauth", хотя она уже создана

**Comment by nikitoSha** [comment]
Скорее всего, нужно в SQL-запросе просто проверять наличие таблицы (if not exist)

**Comment by nikitoSha** [comment]
Провели тесты при работе без рекламного набора инструментов - ошибки исчезли.
Наблюдаем новые стэки ошибок всё по той же теме с sqlite.

**1. (Lenovo A6010, android 5.0.1)**
`android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:634)
	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:320)
	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:294)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1167)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1156)
	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
	at org.chromium.android_webview.HttpAuthDatabase$1.run(HttpAuthDatabase.java:12)
`

**2. (Galaxy A7(7.0), Galaxy J3 (5.1), Honor 5A(5.1.1))**
`android.database.sqlite.SQLiteException: table httpauth already exists(Sqlite code 1),(OS error - 2:No such file or directory) at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method) at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:743) at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754) at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64) at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1756) at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1680) at org.chromium.android_webview.HttpAuthDatabase$1.run(HttpAuthDatabase.java:19)`

**3. (Galaxy A7(7.0), Galaxy J3 (5.1), Huawei(8.0), 4good (7.0))**
`android.database.sqlite.SQLiteException: table httpauth already exists (code 1)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:750)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1707)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1636)
	at alL.run(PG:19)
`

Из 35 новых пользователей вылетает софт у 15-18 человек. Это беда, нужно решать вопрос. :(
Не понятно, почему стек ошибок не указывает на конкретные классы, вызывающие функционал СУБД. 100% информация, что мы сами не использовали СУБД и пара сторонних библиотек тоже.

**Comment by nikitoSha** [comment]
Прикрепил развернутый лог ошибок из Фабрики. Прошу помочь в решении проблемы, как можно скорей, т.к. у пользователей очень часто заваливается приложение. :(
[ru.rsit.agentovnet_issue_1_crash_5B3049F9001C0001448A40746689A32B_DNE_0_v2.txt](https://github.com/yandexmobile/yandex-ads-sdk-android/files/2131763/ru.rsit.agentovnet_issue_1_crash_5B3049F9001C0001448A40746689A32B_DNE_0_v2.txt)

**Comment by satsakul** [comment]
Добрый день. Мы постараемся разобраться с проблемой и дать рекомендации для Вас.
На данный момент мы видим, что Вы вызываете загрузку рекламных объявлений из фонового потока. Является ли это причиной данной проблемы мы пока не знаем, но рекомендуем Вам делать любые манипуляции с view из главного потока.

**Comment by nikitoSha** [comment]
@satsakul , добрый. Да, я загружаю рекламу не в главном потоке, т.к на многих устройствах интерфейс просто замораживается. Оно и логично, там же adRequest, он работает с сетью ведь? Это нужно делать в фоновых потоках и в главном по факту загрузки рекламы отображать ее во вьюхе. Может, как-то можно нормально получить по сети рекламу в фоновом и отобразить ее в главном потоке (во view)?

**Comment by satsakul** [comment]
Необходимую работу по работе с сетью в фоновом потоке мы берем на себя. Поэтому проблем у Вас не должно быть с этим. Ничего "замораживаться" не должно. 

> Скорее всего, нужно в SQL-запросе просто проверять наличие таблицы (if not exists)
Мы не делаем SQL-запросов в рекламной библиотеке. Они есть в библиотеке AppMetrica, но судя по стектрейсу - проблема вознивает на webview, а AppMetrica не работает с webview.

Ваше приложение построено на работе с webview?

**Comment by nikitoSha** [comment]
Нет, в том-то и дело, что полностью нативное и не используется нигде виджет WebView. Понимаю, что не должно замораживаться приложение, но замораживается, когда загружаю баннер и межстраничник без принудительной работы в фоновом потоке. Надеюсь, у нас получить решить вопрос.:)

**Comment by nikitoSha** [comment]
Подставился сегодня - выложил в доступ обновление, где убрал запуск в фоновом потоке запроса на рекламу.
[ru.rsit.agentovnet_issue_2_crash_5B3133BE011A000145D184095EAF8621_DNE_0_v2.txt](https://github.com/yandexmobile/yandex-ads-sdk-android/files/2132937/ru.rsit.agentovnet_issue_2_crash_5B3133BE011A000145D184095EAF8621_DNE_0_v2.txt)

**Comment by nikitoSha** [comment]
У меня есть подозрения, что приложение вываливается во время показа межстраничной рекламы. Например, когда человек где-то нажимает или проводит пальцем в пределах рекламного блока.

**Comment by nikitoSha** [comment]
Лог показывает, что что-то не так происходит здесь:
com.yandex.metrica.impl.ob.eo$a.run (SourceFile:82)

и здесь:
com.yandex.metrica.impl.ob.f$1.run (SourceFile:90)

**Comment by nikitoSha** [comment]
Отключили рекламу, сбоев не было. Включили обратно - повалились:

> Fatal Exception: android.database.sqlite.SQLiteException: table httpauth already exists (code 1)
#################################################################
Error Code : 1 (SQLITE_ERROR)
Caused By : SQL(query) error or missing database.
	(table httpauth already exists (code 1))
#################################################################
       at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:878)
       at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
       at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
       at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1814)
       at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1743)
       at org.chromium.android_webview.HttpAuthDatabase$1.run(HttpAuthDatabase.java:1132)

Может, стоит здесь проверить?

> YandexMobileAds.BaseController
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

Реклама загружается у нас сразу по факту запуска приложения в OnCreate() главной активности. На главной у нас список объектов недвижимости и после нажатия на элемент списка показывается межстраничник (перед показом деталей объекта). Люди уходят от нас

**Comment by nikitoSha** [comment]
http://crashes.to/s/6ebbc353ec1

http://crashes.to/s/ef537a2f8e2

**Comment by dmitryfisko** [comment]
Здравствуйте, подскажите:
Какая версия build tools используется при сборке приложения? 
В качестве сборочного toolchain используется "jack and jill"?
ProGuard не используется?

**Comment by nikitoSha** [comment]
@dmitryfisko Здравствуйте, build tools версии 27.0.3, sdk для компиляции версии 27 (8.1 android). 
ProGuard по умолчанию, конфиг стандартный от Андроид Студии, правила не вносил. MinifyEnabled так же выключен.
Как я понял, jack должен подключаться вручную. Сам я не изменял сборочные инструменты. Все стандартно, из коробки для студии 3.1.3. Версия gradle 4.4,  а версия плагина - 3.1.3

**Comment by nikitoSha** [comment]
Использую jre 1.8.0_152

**Comment by nikitoSha** [comment]
Только что прилетел еще один стэк, уже новая ошибка, но в той же степи. Возможно, видео-реклама была включена.

http://crashes.to/s/f747191d211

**Comment by nikitoSha** [comment]
Словил еще один вариант ошибки. Он указывает на один из методов обратного вызова класса межстраничника:

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
       at android.content.ComponentName.<init>(ComponentName.java:130)
       at android.content.Intent.<init>(Intent.java:6359)
       at ru.rsit.agentovnet.fragments.HomeFragment$2.onInterstitialDismissed(HomeFragment.java:158)
       at com.yandex.mobile.ads.impl.ey.B(SourceFile:279)
       at com.yandex.mobile.ads.impl.ey.a(SourceFile:132)
       at com.yandex.mobile.ads.impl.x.onReceiveResult(SourceFile:64)
       at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

Вот код:

            @Override
            public void onInterstitialDismissed() {
                super.onInterstitialDismissed();
                loadPageAd();
                //показать экран объекта
                startActivity(new Intent(getContext(), RentObjectActivity.class)
                        .putExtra("isMineObject", false)
                        .putExtra("object_id", lastClickedObjectID));
            }

По стэку ошибки
> at ru.rsit.agentovnet.fragments.HomeFragment$2.onInterstitialDismissed(HomeFragment.java:158)

строка, где вылетает приложение:
        
    startActivity(new Intent(getContext(), RentObjectActivity.class)

`lastClickedObjectID` не может быть null, т.к. это int (>= 0).
Подозрения падают на getContext() во фрагменте. Может, когда межстраничная реклама закрывается, то getContext() во фрагменте уже null? Само состояние фрагмента сохраняется (список элементов listView и т.п.)

**Comment by nikitoSha** [comment]
По вопросу о компиляторе - да, JACK, но multiDex не подключен. Класс приложения наследуется от Application

**Comment by dmitryfisko** [comment]
Приведённые вами NPE не относятся к коду рекламного SDK.
Правильно понимаю, что при сборке приложения используется Android Plugin версии 3.1.3? Ведь судя по коду Android Plugin 3.1.3, поддержка сборки с Jack была убрана.
На данный момент, пока не удалось воспроизвести описанную вами проблему с SQLiteException.

**Comment by DimaKoz** [comment]
чтобы исключить недопонимание - я такой же пользователь yandex sdk как и вы @nikitoSha.
1)
@nikitoSha у вас же getContext() == null в этой ошибке:
'Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference'. 

2)
По поводу 'android.database.sqlite.SQLiteException: table httpauth already exists (code 1) at' пока идет разбирательство, что и как - я предлагаю попробовать удалять или таблицу, или эту БД, или просто переименовать название БД, до запуска 'WebView', предполагаю, что к ней должен быть доступ из приложения.
https://github.com/pwnall/chromeview/blob/master/src/org/chromium/android_webview/HttpAuthDatabase.java#L31

И так же логгировать содержимое объекта Interstitial, Fabric позволяет это делать, возможно это связано с каким-нибудь одним рекламным объявлением( что-то сделал не так рекламодатель)

**Comment by nikitoSha** [comment]
@DimaKoz 

    я предлагаю попробовать удалять или таблицу, или эту БД, или просто переименовать название БД, до запуска 'WebView'

Каким образом? Я выше писал, что нигде не используется в приложении ни СУБД, ни ВебВью. Поэтому вынес предположение, что ВебВью используется при показе межстраничной рекламы.

@dmitryfisko да, используется плагин Gradle версии 3.1.3. Никаких манипуляций с компилятором я в жизни не проводил, всё устраивает из коробки, повторюсь.

В общем, только по одной ошибке у 15 пользователей 15 раз вылет приложения. Лично я сам на доступных устройствах не смог воспроизвести ошибку при работе с приложением. Точнее, один единственный раз вылетело приложение при запуске, почти сразу после отображения списка недвижимости. Думаю, что вылетело тогда, когда загрузился рекламный блок (межстраничник). К сожалению, в этот момент устройство не было подключено ни через Adb, ни к фабрике.

Выхода нет, придется отключать показ межстраничной рекламы.

**Comment by nikitoSha** [comment]
@dmitryfisko 

    Приведённые вами NPE не относятся к коду рекламного SDK.

Приведен только один и, конечно, он не относится непосредственно к коду SDK Ads. Я показал, где словил его - в методе обратного вызова я.рекламы.
Вы ориентируйтесь, пожалуйста, на другие стеки ошибок, которые Выше. Их больше, чем один NPE.

**Comment by dmitryfisko** [comment]
@nikitoSha cпасибо, локализировали причину "android.database.sqlite.SQLiteException: table httpauth already exists", проблема будет исправлена в ближайшем обновлении SDK.
Проблема связана с параллельной загрузкой нескольких рекламных объявлений и может проявляться при первом старте установленного приложения.

В качестве временного решения, должно помочь выполнение следующего кода до начала загрузки рекламного объявления при первом старте приложения :
```
try {
    WebViewDatabase.getInstance(context);
} catch(final Throwable throwable) {
}
```

Также пару рекомендаций:
1) При получении ошибки загрузки объявления, не следует сразу выполнять повторную загрузку объявления, лучше повторить лишь через некоторый промежуток времени, т.к. иначе при запуске приложения без интернета произойдёт зацикливание.
2) В приложении есть баннеры различных размеров, но для них используется один Block ID. По этой причине для баннера 320x50 на экране "Сниму", может прийти реклама размера 300x250, которая соответственно не сможет отобразиться в баннере меньшего размера. Следует использовать Block ID настроенный только под соответствующий размер баннера.
3) В onDestroy следует обнулять ссылку на слушатель загрузки рекламного объявления.

**Comment by nikitoSha** [comment]
@dmitryfisko я очень рад, что Вы нашли причину. Обновил исходный код в соответствии с рекомендациями. Надеюсь, что проблема не будет проявляться, а так же очень жду обновление библиотеки. Спасибо!

**Comment by nikitoSha** [comment]
Всё, сбоев нет теперь вообще, 100% пользователей без падений приложения.
