### ISSUE TITLE
Interstitial реклама отображается под statusbar-ом и навигацией (WindowInsets + Android 15)

### ISSUE THREAD

**Issue by DaniilPavlenko** [yandexmobile/yandex-ads-sdk-android#290]
**Версия SDK: 7.6.0**

Если поднять `targetSdk` приложения до `35`, то поверх Interstitial рекламы отображаются statusbar и навигация.

<details>
<summary>1. Нижнюю кнопку перекрывает панель навигации, часть контента скрыта вырезом под камеру</summary>

![edge-to-edge-actual](https://github.com/user-attachments/assets/296d1895-d863-462a-8613-cdad8fa29cc1)
</details>

<details>
<summary>2. Часть контента скрыта вырезом под камеру</summary>

![edge-to-edge-actual-2](https://github.com/user-attachments/assets/c26fe977-ea57-470e-8ff3-1085d9e69e74)
</details>

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3925. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3925 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день! Изучаем проблему, вернемся с ответом

**Comment by DaniilPavlenko** [comment]
Исправлено в [7.8.0](https://ads.yandex.com/helpcenter/ru/dev/android/changelog-android#2024)
