### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by nikitoSha** [yandexmobile/yandex-ads-sdk-android#31]
Добрый день. Ребята, вылезла одна ошибка. Первый раз, видимо, редкая.

	Fatal Exception: java.lang.NullPointerException
		android.webkit.WebViewClassic.loadDataWithBaseURL (WebViewClassic.java:3645)
		android.webkit.WebView.loadDataWithBaseURL (WebView.java:853)
		com.yandex.mobile.ads.impl.z.b (SourceFile:142)
		com.yandex.mobile.ads.impl.ed.a (SourceFile:31)
		com.yandex.mobile.ads.impl.ef$1.a (SourceFile:93)
		com.yandex.mobile.ads.impl.eh$1.a (SourceFile:1048)
		com.yandex.mobile.ads.impl.ll.b (SourceFile:1060)
		com.yandex.mobile.ads.impl.kj$a.run (SourceFile:105)
		android.os.Handler.handleCallback (Handler.java:615)
		android.os.Handler.dispatchMessage (Handler.java:92)
		android.os.Looper.loop (Looper.java:137)
		android.app.ActivityThread.main (ActivityThread.java:4960)
		java.lang.reflect.Method.invokeNative (Method.java)
		java.lang.reflect.Method.invoke (Method.java:511)
		com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1038)
		com.android.internal.os.ZygoteInit.main (ZygoteInit.java:805)
		dalvik.system.NativeStart.main (NativeStart.java)

[http://crashes.to/s/f99b3ec9203](url)

**Comment by alexander-kulikovskiy** [comment]
Добрый день.
Проблема исправлена. Ближайшая версия выйдет с фиксом.

**Comment by satsakul** [comment]
Вышла версия рекламной SDK с фиксом данной проблемы.
