### ISSUE TITLE
Можно ли использовать с нативной рекламой Яндекс Метрику версии 3.1.0?

### ISSUE THREAD

**Issue by DimaKoz** [yandexmobile/yandex-ads-sdk-android#32]
Добрый день.
Мы используем библиотеку `com.yandex.android:mobileads:2.72` для показа нативной рекламы.
У вас в документации приведен пример, что Яндекс Метрика должна быть `com.yandex.android:mobmetricalib:2.73 ` или выше.

Можем ли мы использовать Яндекс Метрику `com.yandex.android:mobmetricalib:3.1.0`  и будут ли засчитаны показы рекламы, если мы будем использовать данную версию Яндекс Метрики?

**Comment by satsakul** [comment]
Добрый день.
Да, последняя версия AppMetrica с которой мы проводили тестирование - это com.yandex.android:mobmetricalib:3.1.0

Её использовать можно.

**Comment by satsakul** [comment]
Версия рекламной SDK 2.73 совместима с AppMetrica 3.2.2
