### ISSUE TITLE
Adview в ViewHolder RecyclerView

### ISSUE THREAD

**Issue by BlackDizel** [yandexmobile/yandex-ads-sdk-android#34]
При использовании AdView в RecyclerView с разными BlockId и параметрами при переиспользовании вьюхи вылетает ошибка Block ID can't be set twice. Как корректно переиспользовать AdView в recyclerview?

**Comment by satsakul** [comment]
Добрый день. 
В целом, лучше воспользоваться нативной рекламой при работе с recyclerview.
Если же Вы планируете использовать именно баннерную рекламу, необходимо помнить, что устанавливать blockId для AdView можно только один раз.
