### ISSUE TITLE
Проблемы с навигацией по документации

### ISSUE THREAD

**Issue by but4er007** [yandexmobile/yandex-ads-sdk-android#35]
Здравствуйте! Вопрос не по теме, но не нашел, куда можно написать еще.
Пытался посмотреть документацию на сайте, но при переключении вкладок через навигационное меню появляется пустой экран.
https://tech.yandex.ru/mobile-ads/doc/dg/android/quick-start/native-docpage/

**Comment by mobile-ads-github** [comment]
Добрый день! Если вы используете Яндекс.Браузер, то отключите, пожалуйста, блокировщик рекламы AdGuard. Мы уже знаем об этой проблеме и сообщили разработчикам браузера.

**Comment by but4er007** [comment]
помогло, спасибо
