### ISSUE TITLE
Test blockId for an NativeImageAd

### ISSUE THREAD

**Issue by Lex1717** [yandexmobile/yandex-ads-sdk-android#37]
Hi, I'm implementing support of the nativeImageAd in my app. Now I'd like to test it's appearance, but there are only two test blockId: one for a ContentAd and another for a AppInstallAd. 
How can I check appearance of an nativeImageAd banner?
Thanks in advance!

**Comment by kried** [comment]
Hi
There is currently no test block for NativeImageAd. We will add it soon.

**Comment by satsakul** [comment]
Hello. You can try to use **R-M-DEMO-native-video**
