### ISSUE TITLE
спасибо, локализировали причину "android.database.sqlite.SQLiteException: table httpauth already exists", проблема будет исправлена в ближайшем обновлении SDK.

### ISSUE THREAD

**Issue by booksmaster** [yandexmobile/yandex-ads-sdk-android#39]
Здравствуйте, @dmitryfisko , прошу помощи. Получаю такую же ошибку у примерно 2% пользователей. сдк 2.91. Интер не использую, только банер. 

Текст ошибки из файрбейс вот такой:
Fatal Exception: android.database.sqlite.SQLiteException
table httpauth already exists (code 1)
android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount (SQLiteConnection.java)
android.database.sqlite.SQLiteConnection.executeForChangedRowCount (SQLiteConnection.java:744)
android.database.sqlite.SQLiteSession.executeForChangedRowCount (SQLiteSession.java:754)
android.database.sqlite.SQLiteStatement.executeUpdateDelete (SQLiteStatement.java:64)
android.database.sqlite.SQLiteDatabase.executeSql (SQLiteDatabase.java:1676)
android.database.sqlite.SQLiteDatabase.execSQL (SQLiteDatabase.java:1605)
org.chromium.android_webview.HttpAuthDatabase$1.run (HttpAuthDatabase.java:1132)

Заранее спасибо.

**Comment by dmitryfisko** [comment]
Здравствуйте, извините за долгий ответ. Проблема будет исправлена в ближайшем релизе 2.92, планируем выпустить релиз в течении этой недели.
В качестве временного решения можно добавить следующий вызов перед загрузкой рекламы:
`try {
    WebViewDatabase.getInstance(context);
} catch(final Throwable throwable) {
}`

**Comment by booksmaster** [comment]
спасибо за ваш ответ. пока мне удалось купировать проблему на 80-90%
добавив паузу в 2 мне между любыми действиями с рекламой. например пауза
между покрытием и показом баннера. или запросом на загрузку интера после
показа предыдущего. но ошибка ушли не на 100%. известно ли, когда
планируется выпустить этот патч? в смысле обнову

пн, 17 июн. 2019 г., 11:59 Dmitry Fisko <notifications@github.com>:

**Comment by dmitryfisko** [comment]
Планируем в течении этой недели выпустить версию SDK с исправлением.

**Comment by booksmaster** [comment]
> Планируем в течении этой недели выпустить версию SDK с исправлением.

Здравствуйте, Дмитрий! Нет ли новостей по поводу даты выхода новой версии сдк?

**Comment by dmitryfisko** [comment]
Добрый день, к сожалению дата релиза SDK сместилась
Планируем выпустить релиз в среду

**Comment by booksmaster** [comment]
Простите, что беспокою. Нет ли новостей? @dmitryfisko

**Comment by dmitryfisko** [comment]
Не ожидаем изменений в сроках релиза SDK, планируем выпустить сегодня вечером

**Comment by dmitryfisko** [comment]
Доброе утро, вышел релиз SDK 2.100 с исправлением данной проблемы

**Comment by booksmaster** [comment]
Все отлично. Обновили несколько игр. Ошибок нет, реклама есть. Продолжаем обновлять остальные. Спасибо большое!

**Comment by satsakul** [comment]
Спасибо
