### ISSUE TITLE
Proguard

### ISSUE THREAD

**Issue by thest1** [yandexmobile/yandex-ads-sdk-android#4]
Очень хочется, чтобы в библиотеке появился разумный proguard конфиг.

**Что мне нужно:** чтобы proguard удалял из моего apk все классы, которые мне не нужны. Например в библиотеке есть полноэкранная реклама, native реклама. Я ими не пользуюсь соответственно хочу, чтобы они не занимали зря место в моём apk. Кроме них уверен что proguard найдёт ещё много чего интересного, что можно легко вырезать.

**Что есть сейчас:** вы в конфиге указали, чтобы proguard вашей библиотеки вообще не касался. То есть все классы, которые для работы моего приложения не нужны, будут всё-равно в него запакованы. Возможно вы просто перестраховались и необходимости в этом нет совсем.

**Что я предлагаю сделать:** удалить строку _keep class com.yandex.mobile.ads.** { *; }_. Собрать и протестировать что получится. Возможно обнаружатся какие-то классы, которые нам нужны, но proguard их ошибочно вырезал. Вот только их и указать в конфиге. Хотя таких классов может и нет совсем.

**Что мне не нужно:** обфускация. Я обфускацией не пользуюсь так что меня не волнует, если вы в конфиге запретите обфускацию имён классов. Возможно кому-то другому это и нужно, но лично для меня это не актуально сейчас. Всё что я пишу касается только фазы shrink, то есть вырезания из apk неиспользуемых классов https://stuff.mit.edu/afs/sipb/project/android/sdk/android-sdk-linux/tools/proguard/docs/index.html#manual/introduction.html.

**Почему для меня это важно:** Я стараюсь, чтобы моё приложение было более компактным. И гугл нам постоянно напоминает обращать на это внимание. Меня расстраивает, когда каждая из используемых библиотек с каждым обновлением становится всё больше и больше. Изменения размера конечно обычно не большие, но они постоянно накапливаются. Хотя бы proguard помогает с этим как-то справлять. Но не в вашем случае к сожалению. Очень надеюсь на исправление. 

Спасибо!

**Comment by yvasileuski** [comment]
В документации написано, что библиотека доступна в формате jar. Это значит, что вы можете настроить любые правила обфускации под собственный проект. В том числе не добавлять строку keep class com.yandex.mobile.ads, собрать и протестировать полученное apk. Скажите, что еще предлагается исправить? И как в этом случае разработчики смогут гарантировать качество итогового sdk?

**Comment by thest1** [comment]
Да, всё правильно. Я имею возможность убрать строку keep и proguard вырежет из вашей библиотеки всё лишнее. Но к сожалению proguard не идеален. Он может случайно вырезать какой-то нужный класс, который использовался не очевидным образом и proguard этого не понял. Визуально это может никак не проявиться, я проблемы не замечу, опубликуюсь и потом всё развалиться и перестанет работать. Ну не смертельно конечно. Я всё это сделаю и потом отпишусь вам о результатах.

Моё же предложение сделать иначе. Для примера посмотрите proguard конфиг любой гугловской библиотеки. Там разработчики библиотеки уже сами протестировали работу proguard со своей библиотекой, выявили те скользкие классы с которыми proguard может не справиться, указали в конфиге только их. Все остальные классы proguard-у разрешено удалять если он сочтёт их неиспользуемыми.

В идеале конечно у вас нет никаких скользких классов и никаких проблем от использования proguard вы не ожидаете. Но ведь по какой-то причине вы запретили proguard касаться ваших классов. Значит всё-таки мне стоит ожидать каких-то сюрпризов если я просто уберу keep как вы мне предложили. Ну увидим.

**Comment by thest1** [comment]
Сделал как вы предложили - просто удалил строку keep class com.yandex.mobile.ads. Вроде бы всё в порядке, не падает, эффективность работы рекламы вроде бы не пострадала. 
Хорошо бы вы удалили эту строку со своей стороны если она на самом деле не нужна. Чтобы я знал, что вы официально поддерживаете такой режим и мне не стоит опасаться каких-то проблем в будущем. Спасибо!

**Comment by satsakul** [comment]
Спасибо. В данный момент мы работаем над этой задачей. В том числе над оптимизацией кол-ва методов и веса поставляемой библиотеки.
