### ISSUE TITLE
How to disable separated process

### ISSUE THREAD

**Issue by OlegTarashkevich** [yandexmobile/yandex-ads-sdk-android#41]
Добрый день, 

@satsakul Спасибо за SDK!

Замечено, что в приложении появляется отдельный процесс после добавления `implementation 'com.yandex.android:mobmetricalib:3.6.4'`

Можно ли убрать отдельный процесс и зачем он нужен? В приложении уже могут быть другие процессы, а тут от SDK появляется. Каждый процесс - это дополнительная нагрузка на память. Хочется легковесной SDK.

![Screen Shot 2019-07-02 at 21 37 52](https://user-images.githubusercontent.com/13828110/60538247-e6e12e00-9d12-11e9-93fb-b2e7f44ca716.png)

**Comment by satsakul** [comment]
Добрый день. Рекламная SDK работает в связке с AppMetrica, которая запускается в отдельном процессе. На данный момент от этого не уйти.

**Comment by OlegTarashkevich** [comment]
@satsakul Спасибо за ответ. Подскажите пожалуйста, AppMetrica используется только для аналитики SDK или она отправляет важные данные самой рекламной sdk, например клики или показы? Можно ли безболезненно выпилить AppMetrica?

Мне нужно максимально уменьшить количество методов и классов в apk. Рассматриваю вариант подмены имен классов и методов на пустые путем создания кастомной AppMetrica.

**Comment by satsakul** [comment]
@OlegTarashkevich AppMetrica жизненно необходима для рекламной SDK. Она не только отправляет аналитику SDK, но и предоставляет рекламе необходимые данные для показа рекламы. Поэтому нет, безболезненно выпилить AppMetrica не получится. Может перестать засчитываться реклама. 
Рекламное SDK и АппМетрика добавляют не так много методов и классов, особенно после включения прогуарда.

**Comment by OlegTarashkevich** [comment]
Можно ли безболезненно переопределить сервисы для AppMetrica, убрав `android:process=":Metrica"` ?

` 
        <service
            android:name="com.yandex.metrica.MetricaService"
            android:enabled="true"
            android:exported="true"
            android:process=":Metrica"
            tools:ignore="ExportedService" >
            <intent-filter>
                <category android:name="android.intent.category.DEFAULT" />

                <action android:name="com.yandex.metrica.IMetricaService" />

                <data android:scheme="metrica" />
            </intent-filter>

            <meta-data
                android:name="metrica:api:level"
                android:value="81" />
        </service>
        <service
            android:name="com.yandex.metrica.ConfigurationService"
            android:enabled="true"
            android:exported="false"
            android:process=":Metrica"
            tools:ignore="ExportedService" >
            <meta-data
                android:name="metrica:configuration:api:level"
                android:value="3" />

            <intent-filter>

                
                
                <action android:name="com.yandex.metrica.configuration.ACTION_INIT" />
            </intent-filter>
        </service>
        <service
            android:name="com.yandex.metrica.ConfigurationJobService"
            android:enabled="true"
            android:exported="false"
            android:permission="android.permission.BIND_JOB_SERVICE"
            android:process=":Metrica" >
        </service>`

**Comment by OlegTarashkevich** [comment]
AppMetrica - это нечто ужасное. Кто придумал добавлять отдельный процесс? Я понимаю, что вопрос не к yandex ads. Но из-за этой метрики падают приложения, т.к. нельзя безболезненно реализовать сторонние библиотеки, такие как WorkManager, ActiveAndroid и др.. Запускается отдельный процесс Metrica, который пробует запустить все, что находится в Application классе, но все не может и приложение падает. Решения с ContentProvider не подошли: [link](https://medium.com/@programmerr47/custom-work-manager-initialization-efdd2afa6459)

Одно дело просто добавить рекламную sdk, а другое думать как решить проблему с ее зависимостями.

Для нас делать рефакторинг в 6 приложениях из-за AppMetrica становится нецелесообразно и дорого.

Поэтому, к сожалению, решили пока-что отказаться от Yandex ads.

**Comment by mobile-ads-github** [comment]
Здравствуйте! Возможно, команда AppMetrica поможет с проблемой, и мы сможем прийти к общему решению.
@alexklints, привет. Можешь ли ты подсказать нашему партнеру, как избежать сложностей, описанных выше, при интеграции АппМетрика и рекламной SDK?

**Comment by alexklints** [comment]
Привет. 
Отдельный процесс нужен для следующих целей:
1. Не отъедать память у основного процесса приложения (jvm-лимит памяти действует в пределах процесса);
2. Не влиять на работу приложения с точки зрения производительности (фоновые процессы имеют меньший приоритет);
3. Не влиять на стабильность приложения (падения фонового процесса не влияют на основной);
4. Надежного доставлять креши (при падении основного процесса, отдельный процесс обеспечивает надежную доставку сведений о падении).

Наконец, с поздних версий Android система имеет ряд оптимизаций по работе с процессами, включая их кэширование. Чем меньше процесс, тем выше вероятность, что он будет кэширован на стороне системы и повторный его запуск потребит меньше ресурсов. 

Технически, AppMetrica сохранит работоспособность, если перенести все компоненты в основной процесс. Но возможны определенные сайд-эффекты, в соответствии с пунктами выше.
Большинство решений, описанных выше вроде WorkManager объясняют в документации, что их нужно запускать для основного процесса. В документации AppMetrica есть информация о том, как нужно обыгрывать ситуации с такими инструментами:
https://appmetrica.yandex.com/docs/mobile-sdk-dg/concepts/android-errors.html#android-errors__third-party-library-init
https://appmetrica.yandex.com/docs/mobile-sdk-dg/concepts/android-features.html

**Comment by OlegTarashkevich** [comment]
@mobile-ads-github @alexklints Спасибо за детальный ответ!

Возможно AppMetrica хороша, если ее целенаправлено добавляет в проект сам разработчик и она служит для приложения. 

У нас задача была добавить рекламную sdk с написанием минимального дополнительного кода, без изменения текущего. Мы не хотим обыгрывать решения вокруг AppMetrica. Нам нужно просто добавить рекламную SDK без головной боли, как это было сделано с AdMob, Facebook, Mopub, Unity ads. Был написан только код показа рекламы, никаких обходных решений. Важно чтобы все работало из коробки. 

Вероятно, перевести в основной процесс будет выходом, но придется тестировать.

**Comment by OlegTarashkevich** [comment]
Добрый день,

Планируется ли отказ от AppMetrica SDK, как необходимой библиотеки для работы с YandexMobileAds SDK?

**Comment by satsakul** [comment]
Добрый день.
В настоящее время мы не планируем отказываться от AppMetrica SDK, так как она нам необходима для работы рекламной SDK.

Мы рассмотрим вариант создания отдельного модуля AppMetrica SDK c ограниченным набором функциональности для использования его в рекламной SDK. Однако сейчас точные сроки назвать мы не можем. Как только такая информация появится, мы обязательно свяжемся с Вами.
Большое спасибо за фидбек.
