### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by mshq37** [yandexmobile/yandex-ads-sdk-android#43]
В версии 2.100 Activity всё еще утекает. В глубине NativeContentAd всё еще содержит ссылку на NativeContentAdView. Таким образом NativeContentAdView утекает через WeakHashMap в static объекте в глубине библиотеки, т.к. NativeContentAd является "значением" в ней, что блокирует gc для "ключа" NativeContentAdView.

**Comment by mobile-ads-github** [comment]
Здравствуйте! Спасибо, мы проверим наличие лика.

**Comment by DimaKoz** [comment]
Добрый день. 

Я тоже замечал, что если произвести байндинг NativeContentAd с NativeContentAdView, то потом утечка идет, если пытаешься сохранить для дальнейшего переиспользования NativeContentAd. 

После того, как я заметил утечку в рекламном SDK, мне пришлось отказаться от хранения NativeContentAd, которые уже были хотя бы раз связаны с рекламной вьюшкой. 
В результате сейчас, скажем так, "не очень" соотношение между отрисовками мобильных RTB блоков и их показами(например, по одному из RTB блоку в абсолютных числах за 30 дней - 107 891 857 отрисовок к 5 855 526 показам). 
Т.е. мне сейчас необходимо улучшить это отношение и, без хранения и переиспользования NativeContentAd(показ которых не был засчитан) это тяжело сделать.

Собственно, вопрос в том, есть ли какой-нибудь прогресс с этим issue и могу ли я снова реализовать переиспользование без опасения, что будут утечки?

**Comment by dmitryfisko** [comment]
Здравствуйте. На данной момент memory leak в SDK не устранён, но вы можете воспользоваться временным решением. Для рекламных объектов которые были привязаны к ViewGroup, вызывать bind с пустыми View созданных с application context и очищать листенеры. Реализация такого метода:

```
removeAllClickListeners(boundNativeAdView);

for (final NativeGenericAd nativeAd : nativeAds) {
    try {
        final Context applicationContext = context.getApplicationContext();
        final FrameLayout nativeAdView = new FrameLayout(applicationContext);
        final NativeAdViewBinder binder = new NativeAdViewBinder.Builder(nativeAdView)
                .setAgeView(new TextView(applicationContext))
                .setBodyView(new TextView(applicationContext))
                .setCallToActionView(new Button(applicationContext))
                .setDomainView(new TextView(applicationContext))
                .setFaviconView(new ImageView(applicationContext))
                .setFeedbackView(new Button(applicationContext))
                .setIconView(new ImageView(applicationContext))
                .setImageView(new ImageView(applicationContext))
                .setMediaView(new MediaView(applicationContext))
                .setPriceView(new TextView(applicationContext))
                .setRatingView(new RatingView(applicationContext))
                .setReviewCountView(new TextView(applicationContext))
                .setSponsoredView(new TextView(applicationContext))
                .setTitleView(new TextView(applicationContext))
                .setWarningView(new TextView(applicationContext))
                .build();
        nativeAd.bindNativeAd(binder);
        nativeAd.setAdEventListener(null);
    } catch (final Exception e) {
        Log.e("TAG", "log");
    }
}

private void removeAllClickListeners(@NonNull final ViewGroup view) {
    for (int i = 0; i < view.getChildCount(); i++) {
        final View child = view.getChildAt(i);
        child.setOnClickListener(null);
        if (child instanceof ViewGroup) {
            removeAllClickListeners((ViewGroup) child);
        }
    }
}
```

**Comment by DimaKoz** [comment]
@dmitryfisko Спасибо

**Comment by satsakul** [comment]
Исправлено в версии 2.111
