### ISSUE TITLE
Banner AdSize question

### ISSUE THREAD

**Issue by OlegTarashkevich** [yandexmobile/yandex-ads-sdk-android#49]
Добрый день @mobile-ads-github, @satsakul, @kried,

Подскажите пожалуйста по работе с баннерами. 

В аккаунте установлены разрешенные размеры для баннера: 320×100, 320×50.

<img width="1021" alt="Screen Shot 2019-11-04 at 16 29 58" src="https://user-images.githubusercontent.com/13828110/68124534-af80c900-ff20-11e9-9d4b-a527fd8792bc.png">

Какой размер баннера нужно указать программно, чтобы показывались все разрешенные форматы: 320×100, 320×50?

`  adView.setAdSize(AdSize.flexibleSize());`

или

`  adView.setAdSize(AdSize.BANNER_320x100);`

**Comment by kried** [comment]
Здравствуйте

Баннер будет отображен и в случае использования ```flexibleSize()```,  и в случае ```AdSize.BANNER_320x100```. Вы можете устаносить либо flexible размер, либо размер вью, которая будет не меньше самого большого баннера, в данном случае 320x100.

Разница будет в том, что при использовании flexible размера пустое пространство под баннером будет заполняться адаптивной подложкой. 
<details><summary>Пример</summary>
<img width="372" alt="Flex" src="https://user-images.githubusercontent.com/3630656/68143283-2da19780-ff42-11e9-96ac-c8ff27ed7693.png">
</details>
В случае использования фиксированных размеров подложка не будет отображаться.

Вы можете попробовать разные варианты отображения в [тестовом приложении](https://github.com/yandexmobile/yandex-ads-sdk-android/tree/master/Examples/BannerExample).

**Comment by OlegTarashkevich** [comment]
@kried Спасибо за ответ.

Правильно ли я понимаю, что:
1. `AdSize.BANNER_320x100` не уменьшит количество показов, проигнорируя например размер 320×50.
2. `flexibleSize()` покажет только баннеры размером 320×100 и 320×50, т.к. только эти размеры установлены в моем аккаунте для текущего блока. А банеры большего размера показаны не будут.

С подложкой все понял.

**Comment by kried** [comment]
1. При использовании размера ```AdSize.BANNER_320x100``` в нем будут отображаться и 320×100, и 320×50. Игнорироваться баннер с высотой 50 не будет. Но если бы у вас в аккаунте для этого блока был бы включен размер 728x50, то он бы уже игнорировался, поскольку он не помещается целиком в размер ```AdSize.BANNER_320x100```.

2. На блок в любом случае могут прилетать только те размеры баннеров, которые выставлены в аккаунте. И при ```AdSize.BANNER_320x100```, и при ```flexibleSize()``` будут прилетать только баннеры размером 320×100 и 320×50. Только то, что включено в партнерском интерфейсе.

**Comment by kried** [comment]
Здравствуйте, Олег

Остались ли у вас еще вопросы про использование AdSize?

**Comment by OlegTarashkevich** [comment]
Здравствуйте, спасибо за развернутый ответ. Вопрос решен, с баннерами разобрался.
