### ISSUE TITLE
ios ad on android

### ISSUE THREAD

**Issue by OlegTarashkevich** [yandexmobile/yandex-ads-sdk-android#51]
Добрый день,

Почему на Android устройстве показывается реклама для iOS?

![Screen Shot 2019-11-07 at 18 30 37](https://user-images.githubusercontent.com/13828110/68402843-04287c00-018d-11ea-8321-fc2fff7879b2.png)

**Comment by kried** [comment]
Здравствуйте

На скриншоте представлено отображение демо-блока. На этот блок приходит всегда одна и та же реклама, одинаковая для iOS и Android.

На реальных блоках реклама подбирается в зависимости от девайса. С использование реальных блоков на Android не будет приходить реклама для iOS.

**Comment by kried** [comment]
Здравствуйте, Олег

Остались ли у вас вопросы по поводу подбору этого баннера?

**Comment by OlegTarashkevich** [comment]
Добрый день, спасибо за ответ.
