### ISSUE TITLE
"No ads available" for mediation demo banner blocks in example

### ISSUE THREAD

**Issue by yura3d** [yandexmobile/yandex-ads-sdk-android#54]
https://github.com/yandexmobile/yandex-ads-sdk-android/blob/fabbd27a304e532cd269f93cbb82fbe08d56c7cf/Examples/AdFoxMediationBannerExample/app/src/main/java/com/yandex/adfox/mediation/banner/sample/MainActivity.java#L26-L31

Only `ADFOX_BLOCK_ID` works properly, attempts to use any other always end with error `Ad request completed successfully, but there are no ads available`. Does it should work like this? I think demo blocks should always show us something so that we can test their rendering and behavior.

**Comment by BeaverAA** [comment]
Hello.
I received ads on all blocks in our sample application. Have you tried to use these blocks in our sample application?
If not, then in order for them to work, you need to connect the adapters.
https://tech.yandex.com/mobile-ads/doc/dg/android/adfox/admob-adfox-docpage/
https://tech.yandex.com/mobile-ads/doc/dg/android/adfox/my-target-adfox-docpage/
https://tech.yandex.com/mobile-ads/doc/dg/android/adfox/mopub-adfox-docpage/
https://tech.yandex.com/mobile-ads/doc/dg/android/adfox/facebook-adfox-docpage/
https://tech.yandex.com/mobile-ads/doc/dg/android/adfox/startapp-adfox-docpage/
