### ISSUE TITLE
Не всегда срабатывают методы слушателя InterstitialEventListener

### ISSUE THREAD

**Issue by dubok79** [yandexmobile/yandex-ads-sdk-android#56]
Делаю все как написано в справке по подключению Yandex Ads Mobile
Мне важно получить событие когда полноэкранная реклама закрывается, но это событие onInterstitialDismissed срабатывает далеко не всегда. А события onInterstitialLoaded, onAdClosed и onAdOpened вообще никогда не вызываются. И еще, довольно часто реклама просто не показывается. Думаю какой-то тайм-аут должен быть и должно выходить событие onInterstitialFailedToLoad, но его нет. Ждал больше минуты. Как быть в обоих случаях?

**Comment by dmitryfisko** [comment]
Здравствуйте.
Методы обратного вызова onAdOpened и onAdClosed отрабатывают только в случае, если реклама отображается внутри приложения через встроенный браузер.
Открытие ссылки внутри приложения или во внешнем браузере регулируется с помощью установки флага shouldOpenLinksInApp у объекта InterstitialAd.
https://yandex.ru/dev/mobile-ads/doc/android/ref/com/yandex/mobile/ads/InterstitialEventListener-docpage/

При использовании какого рекламного блока у вас воспроизводилась ошибка с нестабильным вызовом onInterstitialDismissed?
Заметили ли вы повторяющийся сценарий воспроизведения некорректной работы? 
Также подскажите, на каком устройстве у вас воспроизводилась ошибка?
Передайте пожалуйста данную информацию через своего менеджера по работе с партнёрами.

**Comment by dubok79** [comment]
Давайте я здесь отвечу. Я не знаю, где взять такого менеджера.
Рекламный блок - Полноэкранная реклама InterstitialAd или что имеется ввиду?
Мне не нужно открывать ссылки, мне нужно показать рекламу и когда пользователь ее закроет (на крестик или кнопкой "назад") выполнить определенные действия.
Сценарий один. Открываю приложение. Инициализируется реклама, запускается, показывается. Нажимаю на крестик закрытия рекламного блока. Ожидаю выполнения onInterstitialDismissed, что бы выполнить свой дальнейший код.
"Ошибка" появляется на различных устройствах (Redmi Note 4, Redmi Note 7, Lenovo A850+) под разными ОС Android (8, 9, 4.4)

**Comment by dubok79** [comment]
Ошибка не срабатывания onInterstitialDismissed была у меня в коде. Прошу прощения за беспокойство. Все работает как положено.
