### ISSUE TITLE
NativeAdView inheritance

### ISSUE THREAD

**Issue by OlegTarashkevich** [yandexmobile/yandex-ads-sdk-android#62]
@satsakul Здравствуйте,

Хотел бы иметь возможность наследоваться от NativeAdView и реализовать inflate дочерних view внутри него.

Это нужно чтобы показывать пользователю NativeAdView бесшовно, устанавливая предварительно стандартную иконку, заголовок и др. до загрузки самой рекламы. По факту я это делаю извне NativeAdView, что не удобно. К примеру у AdMob есть класс UnifiedNativeAdView с методами доступа к дочерним view, им можно программно назначить начальное значение.

Например:

```
public class CustomNativeAdView extends NativeAdView {

    public CustomNativeAdView(@NonNull Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        init();
    }

    private void init() {
        LayoutInflater.from(getContext()).inflate(R.layout.sdk_template_native_yandex, this);
        TextView title = findViewById(R.id.ad_title);
        // set title before using "bindNativeAd()"
        title.setText("Preloaded title");
    }
}
```

**Comment by satsakul** [comment]
Добрый день. 
Текущее внутренняя логика не позволяет Вам этого сделать. 
Мы рассмотрим предоставление такой возможности при подготовке версии 3.0.0, но не могу Вам гарантировать, что такая возможность появится в ближайшее время
