### ISSUE TITLE
isLoading for NativeAd

### ISSUE THREAD

**Issue by OlegTarashkevich** [yandexmobile/yandex-ads-sdk-android#63]
@satsakul Здравствуйте,

Использую нативную рекламу в RecyclerView, делаю свою реализацию View без использования templates.

Я не могу найти метода, который бы позволил определить что нативная реклама сейчас в процессе загрузки/кэширования данных.
Я хочу избежать сценарий, когда пользователь очень быстро прокручивает список, как результат будет много запросов но мало показов. 
Например у AdMob есть метод `adLoader.isLoading()`. Если он true, я жду и не делаю новый запрос.

Или мне нужно отменять предыдущий запрос перед показом новой рекламы?
`nativeAdLoader.cancelLoading();
nativeAdLoader.loadAd(adRequest);`

**Comment by mobile-ads-github** [comment]
Добрый день.
Мы не планируем добавлять метод ```adLoader.isLoading()```.
По логике нашей библиотеки, каждому вызову метода ```.loadAd``` всегда соответствует вызов одного из колбэков ```NativeAdLoadListener```: ```onAdLoaded``` или ```onAdFailedToLoad```. Исходя из этого, вы можете сами хранить состояние загрузки рекламы в булевой переменной.
