### ISSUE TITLE
Некорректно определяется область объявления в нативном формате

### ISSUE THREAD

**Issue by Android355** [yandexmobile/yandex-ads-sdk-android#65]
Последняя версия SDK 2.140.

Проблема наблюдается с объявлениями, в которых отсутствуют данные для Subview `warning`.

![yandex_ads](https://user-images.githubusercontent.com/63140653/78421586-77adb700-7661-11ea-9e64-7c7c2811ae88.jpg)

1) Большая часть объявления скрыта, все ок.
2) Вид полного объявления, рамка зеленая.
3) Скрыта незначительная часть объявления - рамка красная. 

Так же хотелось бы описать, почему нативный формат мобильной рекламы Yandex имеет наихудшую кастомизацию относительно AdMob и MyTarget:
* Изображения разнообразных соотношений сторон. При нативном виде на всю ширину экрана - объявление может занимать весь экран. Обрезать изображения более 20% запрещено требованиями. В то же самое время такие изображения в web объявлениях обрезаются.
* В 99% случаев для контентных объявлений отсутствует `callToAction`. Свой дефолтный, например "Перейти", либо просто кнопку со стрелкой поставить нельзя.
* Нельзя кастомизировать внешний вид причин закрытия для `feedback`.
* Жестко привязаны все View к определенным классам. К примеру нельзя использовать `ImageButton` для `feedback`, т.к. он требует `Button`.
* Тестовые блоки имеют только один вид объявления, в результате чего на них проверить все варианты нельзя. Отображение реальных объявлений (без засчитывания) было бы куда лучше.
* Нельзя загружать сразу несколько объявлений одним запросом.
* Для контентных объявлений нет иконок.

**Comment by satsakul** [comment]
Добрый день.
Спасибо за подробный фидбек. 
Постараюсь подготовить  подробный ответ на каждый вопрос.

**Comment by Android355** [comment]
Здравствуйте. 
Под первым пунктом имеется ввиду проблема с некорректным определением области объявления? Еще раз перечитал все пункты с требованиями, но так и не понял, что нарушается в объявлении на третьем экране.

**Comment by OlegTarashkevich** [comment]
Мне тоже не хватает ImageButton и иконок для Content объявлений.

Я использую View container в котором по очереди отображается нативная реклама admob, mopub, yandex.
Дизайн для всех источников одинаковый. Для yandex приходится проверять наличие иконки и при ее отсутствии показывать свою заготовленную.

Буду рад, если сможете улучшить.

**Comment by Android355** [comment]
@satsakul, добрый день. Будут какие новости по основному вопросу? Ваш предыдущий ответ не дал опровержения в некорректной работе. В таком случае ставить рекламу от яндекса нецелесообразно.
