### ISSUE TITLE
Crash on Android 8!

### ISSUE THREAD

**Issue by OlegTarashkevich** [yandexmobile/yandex-ads-sdk-android#67]
Добрый день,

23.03.2020 обновлено SDK и приложение отправлено в Google Play:
yandexAdsVersion = '2.120' 
metricaAdsVersion = '3.13.1' 

Появились 157 сбоя на Android 8.

![Screen Shot 2020-04-14 at 21 02 00](https://user-images.githubusercontent.com/13828110/79258624-19b87500-7e94-11ea-84dd-7d3c6b58e1a4.png)
![Screen Shot 2020-04-14 at 21 03 42](https://user-images.githubusercontent.com/13828110/79258631-1c1acf00-7e94-11ea-8e8b-2b1e86849971.png)

**Comment by mobile-ads-github** [comment]
Здравствуйте, данный крэш был исправлен в версии SDK 2.140
