### ISSUE TITLE
Restricted access to the ICCID through the getIccId() API

### ISSUE THREAD

**Issue by AnnaKandel** [yandexmobile/yandex-ads-sdk-android#82]
Hi. 
Recently we received alert from Google team regarding using getIccId() API by our application:
_When Android 10 launched last year, we required developers to obtain privileged permission to access non-resettable identifiers, such as the IMEI. One of those restricted identifiers is the permanent SIM ID, or ICCID, and we encouraged all developers to migrate from any dependency on it.
On Android 11, we further restricted access to the ICCID through the getIccId() API. This change will affect all apps running on Android 11, regardless of the app’s target SDK level._

This api is called from com.yandex.android:mobmetricalib
Could you please check and let us know:
1. If your business logic is able to handle the condition, where the getIccId() API will return a non-null string value on Android 11 devices?

2. Are you considering switching to a privacy-friendly alternative like the [Subscription ID](https://www.google.com/appserve/mkt/p/AD-FnEz8U6FEOMKtCJFd2ka21Mrbs5sqxrI2TuA0d0x7EIHXvgukU574XzWgzcyCCMvO3PwDTRKUjTKHsrahfuiXKDEeOwYIiZECXvGnDsyVOPDVGdUsuQzKSPVtuImmWelcb4jT0L6E7XdEX9AFZkzC8RKhukI1V5idHXKGqKY-)?

**Comment by mobile-ads-github** [comment]
Hi. Thank you for the report! This problem is connected with AppMetrica Android SDK. Please transfer your issue to the AppMetrica Github repository for details about the progress of issue resolving.
AppMetrica SDK repository:
https://github.com/yandexmobile/metrica-sample-android

**Comment by mobile-ads-github** [comment]
Problem fixed in AppMetrica Android SDK 3.16.1
