### ISSUE TITLE
Планируется ли сделать API для Flutter

### ISSUE THREAD

**Issue by Dimitry82** [yandexmobile/yandex-ads-sdk-android#85]
Доброго дня!

Планируется ли создание пакета для Flutter?

**Comment by mobile-ads-github** [comment]
Здравствуйте

В ближайшее время добавление поддержки для Flutter не планируется.

**Comment by kovardin** [comment]
@Dimitry82 может ты уже и не занимаешься мобилками. 2 года аж.. но вот либа для flutter https://pub.dev/packages/flutter_yandex_ads

@satsakul а вы не хотите хоть чутка помочь людям? рассказать про либу у себя в доке

**Comment by Dimitry82** [comment]
О! Здорово) Спасибо огромное)
