### ISSUE TITLE
Изменяется цвет фона в приложении после отображения полноэкранного баннера

### ISSUE THREAD

**Issue by subprogram** [yandexmobile/yandex-ads-sdk-android#92]
После загрузки полноэкранного баннера часть (а иногда и вся) активити изменяет цвет на более темный, а экран начинает мигать.
На моих устройствах проблема не воспроизводится, но пользователи жалуются. 
Заметил, что проблеме подвержены телефоны с Android 9. В настоящий момент есть жалобы от владельцев следующих устройств: Samsung Galaxy J5 (2017), Samsung Galaxy Note8, Xiaomi Redmi Note 5, Huawei nova 3, Xiaomi Mi A2 Lite

Проблема началась после перехода с версии 2.180 на 3.1.1 (на версии 3.2.0 также воспроизводится)

Видео с воспроизведением проблемы: https://youtu.be/yYxAzhyIDg0

<img src="https://user-images.githubusercontent.com/9901443/107496548-7d89f800-6ba2-11eb-9e63-1e7a710bff4f.jpg" width="30%" height="30%"> <img src="https://user-images.githubusercontent.com/9901443/107496530-79f67100-6ba2-11eb-87ab-fa77707da190.jpg" width="30%" height="30%">

**Comment by mobile-ads-github** [comment]
Здравствуйте.
При обновлении SDK с 2.180 до 3.1.1 в приложении менялась логика отображения баннерной или полноэкранной рекламы?
Какую логику вы используете для отображения одной AdView между несколькими Activity?
Как отобразить полноэкранную рекламу в вашем приложении?
Вы используете WebView в приложении для отображения контента?

**Comment by subprogram** [comment]
> При обновлении SDK с 2.180 до 3.1.1 в приложении менялась логика отображения баннерной или полноэкранной рекламы?

Прошу прощения, посмотрел повнимательнее, нашел более ранний отзыв с жалобой на эту проблему. Получается, что это началось еще в версии SDK 2.150. Логика отображения баннерной или полноэкранной рекламы не менялась.

> Какую логику вы используете для отображения одной AdView между несколькими Activity?

В методе ЖЦ `Activity` `onPause()` вызывается `adView.pause()`

В методе ЖЦ `Activity` `onResumeFragments()` выполняются следующие действия:
```
	adView.resume()
	val oldParent = adView.parent
	oldParent.removeView(adView)
	adContainer.requestLayout()
	adView.layoutParams = FrameLayout.LayoutParams(LayoutParams.WRAP_CONTENT, LayoutParams.WRAP_CONTENT, Gravity.CENTER_HORIZONTAL)
	adContainer.addView(adView)
	adView.visibility = View.VISIBLE
	adContainer.visibility = View.VISIBLE
```	
`adContainer` - это `FrameLayout`

> Как отобразить полноэкранную рекламу в вашем приложении?

Полноэкранная реклама начинает загружаться после 3-го по счету запуска приложения с момента установки и если прошло 24 часа с момента первого запуска. Отображается 1 раз за сеанс, при переходе на определенную `Activity` (экран с текстом песни).

> Вы используете WebView в приложении для отображения контента?

WebView в приложении используется только для отображения текста Privacy Policy. Это достаточно редко открываемый экран.

**Comment by subprogram** [comment]
Еще один репорт о проблеме: https://www.youtube.com/watch?v=N5ot-jC1Na4&feature=youtu.be
Из видео видно, что причина именно в полноэкранном баннере. Причем проблемы начинаются не после отображения, а еще раньше - после загрузки рекламы.

**Comment by mobile-ads-github** [comment]
Здравствуйте, на данный момент не удалось воспроизвести проблему.
Подскажите, пожалуйста, как часто данная проблема воспроизводится у пользователей приложения?

**Comment by subprogram** [comment]
У тех, у кого воспроизводится - всегда.
