### ISSUE TITLE
Не скрывает рекламу по нажатию 'Не интересуюсь этой темой'

### ISSUE THREAD

**Issue by SuleymanovTat** [yandexmobile/yandex-ads-sdk-android#96]
Добрый день, пользователи жалуются, что не могут скрыть рекламу.
Загружаются Native реклама, в правом углу пользователи нажимают на крестик, открывается диалог, пользователь нажимает 'Не интересуюсь этой темой', диалог скрывается реклама остается
https://github.com/yandexmobile/yandex-ads-sdk-android/tree/master/Examples/NativeExample

sdk yandex 4.1.0
https://ibb.co/fdzYfX5
https://ibb.co/2jDv0tZ

**Comment by SuleymanovTat** [comment]
https://ibb.co/fdzYfX5
https://ibb.co/2jDv0tZ

**Comment by mobile-ads-github** [comment]
Здравствуйте, спасибо за сообщение о проблеме,  возьмем ее в оборот.
